
import { Badge, Challenge, GamificationStats } from './types';

// Mock data for badges
export const mockBadges: Badge[] = [
  {
    id: '1',
    name: 'Débutant',
    description: 'Premier pas dans le monde du bien-être émotionnel',
    image: '/badges/beginner.png',
    earnedAt: new Date('2025-04-15').toISOString(),
  },
  {
    id: '2',
    name: 'Explorateur',
    description: 'A exploré tous les modules disponibles',
    image: '/badges/explorer.png',
    earnedAt: new Date('2025-04-20').toISOString(),
  },
  {
    id: '3',
    name: 'Entraîneur',
    description: 'A aidé 5 autres utilisateurs dans leur parcours',
    image: '/badges/coach.png',
    earnedAt: null,
  },
];

// Mock data for challenges
export const mockChallenges: Challenge[] = [
  {
    id: '1',
    name: 'Journal quotidien',
    title: 'Journal quotidien',
    description: 'Complétez votre journal émotionnel pendant 7 jours consécutifs',
    points: 100,
    status: 'ongoing',
    progress: 5,
    startDate: new Date('2025-05-01').toISOString(),
    endDate: new Date('2025-05-07').toISOString(),
    total: 7,
  },
  {
    id: '2',
    name: 'Méditation matinale',
    title: 'Méditation matinale',
    description: 'Pratiquez la méditation chaque matin pendant 5 jours',
    points: 75,
    status: 'active',
    progress: 3,
    total: 5,
  },
  {
    id: '3',
    name: 'Partage social',
    title: 'Partage social',
    description: 'Partagez votre expérience avec la communauté',
    points: 50,
    status: 'available',
    progress: 0,
    total: 1,
  },
  {
    id: '4',
    name: 'Équilibre émotionnel',
    title: 'Équilibre émotionnel',
    description: 'Maintenez un score émotionnel stable pendant 3 jours',
    points: 80,
    status: 'active',
    progress: 1,
    total: 3,
  },
  {
    id: '5',
    name: 'Expert en respiration',
    title: 'Expert en respiration',
    description: 'Complétez tous les exercices de respiration disponibles',
    points: 90,
    status: 'active',
    progress: 4,
    total: 6,
  },
  {
    id: '6',
    name: 'Analyse profonde',
    title: 'Analyse profonde',
    description: 'Utilisez l\'outil d\'analyse émotionnelle avancée 3 fois',
    points: 60,
    status: 'available',
    progress: 0,
    total: 3,
  },
  {
    id: '7',
    name: 'Suivi du sommeil',
    title: 'Suivi du sommeil',
    description: 'Enregistrez votre qualité de sommeil pendant 5 jours',
    points: 70,
    status: 'available',
    progress: 0,
    total: 5,
  },
  {
    id: '8',
    name: 'Marathon musical',
    title: 'Marathon musical',
    description: 'Écoutez différentes playlists thérapeutiques pour un total de 120 minutes',
    points: 85,
    status: 'active',
    progress: 75,
    total: 120,
  },
  {
    id: '9',
    name: 'Coach virtuel',
    title: 'Coach virtuel',
    description: 'Interagissez avec le coach IA pendant 10 sessions',
    points: 95,
    status: 'available',
    progress: 0,
    total: 10,
  },
  {
    id: '10',
    name: 'Gratitude quotidienne',
    title: 'Gratitude quotidienne',
    description: 'Notez trois choses pour lesquelles vous êtes reconnaissant chaque jour pendant 5 jours',
    points: 65,
    status: 'available',
    progress: 0,
    total: 5,
  },
];

// Mock gamification stats
export const mockStats: GamificationStats = {
  level: 3,
  points: 340,
  nextLevelPoints: 500,
  badges: mockBadges,
  challenges: mockChallenges,
  completedChallenges: 2,
  activeChallenges: 3,
  streakDays: 5,
  progressToNextLevel: 68,
  totalPoints: 340,
  currentLevel: 3,
  badgesCount: 2,
  pointsToNextLevel: 160,
  recentAchievements: [
    {
      type: 'badge',
      id: '2',
      name: 'Explorateur',
      date: new Date('2025-04-20').toISOString(),
    },
    {
      type: 'challenge',
      id: '9',
      name: 'Explorateur de bien-être',
      date: new Date('2025-04-18').toISOString(),
    },
  ],
};
