// @ts-nocheck
import type { RouteMeta } from '../schema';

export const B2B_ROUTES: readonly RouteMeta[] = [
  {
    name: 'b2b-dashboard-analytics',
    path: '/b2b/dashboard',
    segment: 'manager',
    layout: 'app',
    component: 'B2BDashboardAnalytics',
    guard: true,
    requireAuth: true,
    allowedRoles: ['manager', 'admin'],
  },
  {
    name: 'b2b-reports-heatmap',
    path: '/b2b/reports',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    guard: true,
    requireAuth: true,
    component: 'B2BReportsHeatmapPage',
  },
  {
    name: 'b2b-org-dashboard',
    path: '/b2b/admin/dashboard',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'OrgDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'b2b-org-settings',
    path: '/b2b/admin/settings',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BSettingsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'b2b-institutional-reports',
    path: '/b2b/institutional/reports',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BInstitutionalReportsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'timecraft-b2b',
    path: '/b2b/admin/timecraft',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'TimeCraftB2BPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'employee-home',
    path: '/app/collab',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BCollabDashboardPage',
    guard: true,
    requireAuth: true,
    aliases: ['/b2b/user/dashboard'],
  },
  {
    name: 'manager-home',
    path: '/app/rh',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BRHDashboardPage',
    guard: true,
    requireAuth: true,
    aliases: ['/b2b/admin/dashboard'],
  },
  // ═══════════════════════════════════════════════════════════
  // B2B FEATURES (EMPLOYEE)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'teams',
    path: '/app/teams',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BTeamsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/teams'],
  },
  {
    name: 'social-cocon-b2b',
    path: '/app/social',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BSocialCoconPage',
    guard: true,
    requireAuth: true,
  },
  // ═══════════════════════════════════════════════════════════
  // B2B ADMIN (MANAGER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'admin-reports',
    path: '/app/reports',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BReportsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/reports'],
  },
  {
    name: 'admin-reports-period',
    path: '/app/reports/:period',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BReportDetailPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-events',
    path: '/app/events',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BEventsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/events'],
  },
  {
    name: 'admin-optimization',
    path: '/app/optimization',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BOptimisationPage',
    guard: true,
    requireAuth: true,
    aliases: ['/optimisation'],
  },
  {
    name: 'admin-security',
    path: '/app/security',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BSecurityPage',
    guard: true,
    requireAuth: true,
    aliases: ['/security'],
  },
  {
    name: 'admin-audit',
    path: '/app/audit',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BAuditPage',
    guard: true,
    requireAuth: true,
    aliases: ['/audit'],
  },
  {
    name: 'admin-music-analytics',
    path: '/app/admin/music-analytics',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'MusicAnalyticsDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-accessibility',
    path: '/app/accessibility',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BAccessibilityPage',
    guard: true,
    requireAuth: true,
    aliases: ['/accessibility'],
  },
  {
    name: 'admin-gdpr-unified',
    path: '/admin/gdpr',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'UnifiedGDPRDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-api-monitoring',
    hidden: true,
    path: '/admin/api-monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'APIMonitoringDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-cron-monitoring',
    hidden: true,
    path: '/admin/cron-monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'GamificationCronMonitoringPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-music-queue',
    hidden: true,
    path: '/admin/music-queue',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'MusicQueueAdminPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-music-metrics',
    hidden: true,
    path: '/admin/music-metrics',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'MusicQueueMetricsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-user-roles',
    hidden: true,
    path: '/admin/user-roles',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'UserRolesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'create-custom-challenge',
    path: '/admin/challenges/create',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'CreateCustomChallengePage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'edit-custom-challenge',
    path: '/admin/challenges/edit/:id',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'EditCustomChallengePage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'challenges-dashboard',
    path: '/admin/challenges',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'ChallengesDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-system-health',
    hidden: true,
    path: '/admin/system-health',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AdminSystemHealthPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-monitoring-dashboard',
    hidden: true,
    path: '/admin/monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'MonitoringDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-ai-monitoring',
    hidden: true,
    path: '/admin/ai-monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AIMonitoringDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-config',
    hidden: true,
    path: '/admin/alert-config',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AlertConfigurationPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-analytics',
    hidden: true,
    path: '/admin/alert-analytics',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AlertAnalyticsDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-templates',
    hidden: true,
    path: '/admin/alert-templates',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AlertTemplatesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-playground',
    hidden: true,
    path: '/admin/alert-playground',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AlertTemplatePlaygroundPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-scheduled-reports',
    hidden: true,
    path: '/admin/scheduled-reports',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'ScheduledReportsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-escalation',
    hidden: true,
    path: '/admin/alert-escalation',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AlertEscalationConfigPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-ai-templates',
    hidden: true,
    path: '/admin/ai-template-suggestions',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AITemplateSuggestionsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-escalation-monitoring',
    hidden: true,
    path: '/admin/escalation/monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'EscalationMonitoringDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'gdpr-cron-monitoring',
    path: '/gdpr/cron-monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'CronMonitoringPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'gdpr-blockchain-backups',
    path: '/gdpr/blockchain-backups',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'BlockchainBackupsPage',
    guard: true,
    requireAuth: true,
    hidden: true,
  },
  {
    name: 'admin-ai-template-suggestions',
    hidden: true,
    path: '/admin/alerts/ai-suggestions',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AITemplateSuggestionsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-ticket-integration',
    hidden: true,
    path: '/admin/tickets/integrations',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'TicketIntegrationConfigPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-ab-test-manager',
    hidden: true,
    path: '/admin/escalation/ab-tests',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'ABTestManagerPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-notification-webhooks',
    hidden: true,
    path: '/admin/escalation/webhooks',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'NotificationWebhooksConfigPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-system-health-dashboard',
    hidden: true,
    path: '/admin/system-health/dashboard',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'SystemHealthDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-executive',
    hidden: true,
    path: '/admin/executive',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'ExecutiveDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-incidents',
    hidden: true,
    path: '/admin/incidents',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'IncidentReportsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-unified-dashboard',
    hidden: true,
    path: '/admin/unified',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'UnifiedAdminDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-cron-setup',
    hidden: true,
    path: '/admin/cron-setup',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'CronJobsSetupPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-tester',
    hidden: true,
    path: '/admin/alert-tester',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'AlertTesterPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-ml-assignment-rules',
    hidden: true,
    path: '/admin/ml-assignment-rules',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'MLAssignmentRulesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-team-skills',
    hidden: true,
    path: '/admin/team-skills',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'TeamMemberSkillsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-module-sync',
    hidden: true,
    path: '/admin/module-sync',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'ModuleSyncPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-recommendation-engine',
    hidden: true,
    path: '/admin/recommendation-engine',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'RecommendationEngineAdminPage',
    guard: true,
    requireAuth: true,
  },
  // app-api-docs supprimé — route dev-only
  {
    name: 'app-b2b-analytics',
    path: '/app/b2b/analytics',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BAnalyticsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/b2b/analytics'],
  },
  {
    name: 'app-b2b-alerts',
    path: '/b2b/alerts',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BAlertsPage',
    guard: true,
    requireAuth: true,
    meta: {
      title: 'Alertes RH - EmotionsCare B2B',
      description: 'Gestion des alertes bien-être anonymisées',
    },
  },
  {
    name: 'b2b-teams',
    path: '/b2b/teams',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BTeamsPage',
    guard: true,
    requireAuth: true,
    meta: {
      title: 'Gestion des Équipes - EmotionsCare B2B',
      description: 'Gestion et suivi du bien-être des équipes',
    },
  },
  {
    name: 'b2b-events',
    path: '/b2b/events',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BEventsPage',
    guard: true,
    requireAuth: true,
    meta: {
      title: 'Événements Bien-être - EmotionsCare B2B',
      description: 'Planification et gestion des événements bien-être',
    },
  },
  {
    name: 'b2b-social-cocon',
    path: '/b2b/social-cocon',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BSocialCoconPage',
    guard: true,
    requireAuth: true,
    meta: {
      title: 'Cocon Social B2B - EmotionsCare',
      description: 'Plateforme collaborative pour le bien-être en entreprise',
    },
  },
  {
    name: 'app-collab-coach',
    path: '/app/collab/coach',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BUserCoachPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'platform-audit',
    path: '/admin/platform-audit',
    segment: 'manager',
    role: 'manager',
    layout: 'app-sidebar',
    component: 'PlatformAuditPage',
    guard: true,
    requireAuth: true,
    meta: {
      title: 'Audit Plateforme - EmotionsCare',
      description: 'Rapport de santé et audit complet de la plateforme',
    },
  },
  // ═══════════════════════════════════════════════════════════
  // GOUVERNANCE PLATEFORME (admin/manager B2B)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'governance-overview',
    path: '/admin/governance',
    segment: 'manager',
    role: 'manager',
    allowedRoles: ['admin', 'manager'],
    layout: 'simple',
    component: 'GovernanceOverviewPage',
    guard: true,
    requireAuth: true,
    meta: {
      title: 'Gouvernance Plateforme',
      description: "Vue d'ensemble de la gouvernance technique et de la conformité.",
    },
  },
  {
    name: 'governance-routing',
    path: '/admin/governance/routing',
    segment: 'manager',
    role: 'manager',
    allowedRoles: ['admin', 'manager'],
    layout: 'simple',
    component: 'RoutingGovernancePage',
    guard: true,
    requireAuth: true,
    meta: { title: 'Gouvernance Routing & Registre' },
  },
  {
    name: 'governance-data',
    path: '/admin/governance/data',
    segment: 'manager',
    role: 'manager',
    allowedRoles: ['admin', 'manager'],
    layout: 'simple',
    component: 'DataGovernancePage',
    guard: true,
    requireAuth: true,
    meta: { title: 'Gouvernance Données & RLS' },
  },
  {
    name: 'governance-observability',
    path: '/admin/governance/observability',
    segment: 'manager',
    role: 'manager',
    allowedRoles: ['admin', 'manager'],
    layout: 'simple',
    component: 'ObservabilityGovernancePage',
    guard: true,
    requireAuth: true,
    meta: { title: 'Gouvernance Observabilité & SLO' },
  },
  {
    name: 'governance-modules',
    path: '/admin/governance/modules',
    segment: 'manager',
    role: 'manager',
    allowedRoles: ['admin', 'manager'],
    layout: 'simple',
    component: 'ModulesGovernancePage',
    guard: true,
    requireAuth: true,
    meta: { title: 'Gouvernance Modules & Flags' },
  },
  // context-lens-duplicate supprimé — doublon de context-lens (ligne ~1007)
  // ═══════════════════════════════════════════════════════════
  // MODULE 18 - Programme de prévention (B2B)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'b2b-prevention-program',
    path: '/b2b/prevention',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BPreventionProgramPage',
    guard: true,
    requireAuth: true,
    aliases: ['/app/rh/prevention'],
  },
  // ═══════════════════════════════════════════════════════════
  // MODULE 39 - Team Wellbeing Dashboard
  // ═══════════════════════════════════════════════════════════
  {
    name: 'team-wellbeing',
    path: '/b2b/team-wellbeing',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'TeamWellbeingDashboard',
    guard: true,
    requireAuth: true,
    aliases: ['/b2b/admin/team-wellbeing'],
    status: 'demo',
  },
  // ═══════════════════════════════════════════════════════════
  // MODULE 40 - Interventions Library
  // ═══════════════════════════════════════════════════════════
  {
    name: 'interventions-library',
    path: '/b2b/interventions',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'InterventionsLibraryPage',
    guard: true,
    requireAuth: true,
    aliases: ['/b2b/admin/interventions'],
    status: 'demo',
  },
  // ═══════════════════════════════════════════════════════════
  // MODULE 41 - Research Export
  // ═══════════════════════════════════════════════════════════
  {
    name: 'research-export',
    path: '/b2b/research-export',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'ResearchExportPage',
    guard: true,
    requireAuth: true,
    aliases: ['/b2b/admin/research-export'],
    status: 'demo',
  },
  // ═══════════════════════════════════════════════════════════
  // MODULE 42 - Institutional QVT Reports
  // ═══════════════════════════════════════════════════════════
  {
    name: 'institutional-report',
    path: '/b2b/institutional-report',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'InstitutionalReportPage',
    guard: true,
    requireAuth: true,
    aliases: ['/b2b/admin/institutional-report', '/b2b/qvt-report'],
    status: 'demo',
  },
] as const;
