// @ts-nocheck
import type { RouteMeta } from '../schema';

export const CONSUMER_ROUTES: readonly RouteMeta[] = [
  {
    name: 'creator-dashboard',
    path: '/creator/dashboard',
    segment: 'b2c',
    layout: 'app',
    component: 'CreatorDashboardPage',
    guard: true,
    requireAuth: true,
  },
  // ═══════════════════════════════════════════════════════════
  // TIMECRAFT - Design du temps
  // ═══════════════════════════════════════════════════════════
  {
    name: 'timecraft',
    path: '/app/timecraft',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'TimeCraftPage',
    guard: true,
    requireAuth: true,
    aliases: ['/timecraft'],
    status: 'beta',
  },
  // ═══════════════════════════════════════════════════════════
  // APP DISPATCHER & DASHBOARDS
  // ═══════════════════════════════════════════════════════════
  {
    name: 'app-gate',
    path: '/app',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'AppGatePage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'consumer-home',
    path: '/app/consumer/home',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CDashboardPage',
    guard: true,
    aliases: ['/app/home', '/b2c/dashboard', '/dashboard'],
  },
  // ═══════════════════════════════════════════════════════════
  // MODULES FONCTIONNELS (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'modules-dashboard',
    path: '/app/modules',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ModulesDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'scan',
    path: '/app/scan',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'B2CScanPage',
    guard: true,
    requireAuth: true,
    aliases: ['/scan', '/app/emotions', '/emotions'],
  },
  {
    name: 'scan-facial',
    path: '/app/scan/facial',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'ScanFacialPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'scan-voice',
    path: '/app/scan/voice',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'ScanVoicePage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'scan-text',
    path: '/app/scan/text',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'ScanTextPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'scan-emoji',
    path: '/app/scan/emoji',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'EmojiScanPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'scan-questionnaire',
    path: '/dashboard/scanner',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'QuestionnaireScannerPage',
    guard: true,
    requireAuth: true,
    aliases: ['/app/scan/questionnaire', '/scanner'],
  },
  // ═══════════════════════════════════════════════════════════
  // BREATH HUB - Hub unifié de respiration (4 modes)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'breath-hub',
    path: '/app/breath-hub',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'BreathHubPage',
    guard: true,
    requireAuth: true,
    aliases: ['/app/breath', '/app/breathing', '/respiration', '/breath'],
  },
  {
    name: 'breathing-dashboard',
    path: '/dashboard/breathing',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'BreathHubPage',
    guard: true,
    requireAuth: true,
    deprecated: true,
    redirectTo: '/app/breath-hub',
  },
  // ═══════════════════════════════════════════════════════════
  // MUSIC HUB - Hub unifié de musique (3 onglets)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'music-hub',
    path: '/app/music-hub',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'MusicHubPage',
    guard: true,
    requireAuth: true,
    aliases: ['/music-hub'],
  },
  {
    name: 'emotional-journal',
    path: '/dashboard/journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'EmotionalJournalPage',
    guard: true,
    requireAuth: true,
    aliases: ['/app/journal/emotional', '/journal'],
  },
  {
    name: 'clinical-assessments',
    path: '/dashboard/assessments',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'ClinicalAssessmentsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/assessments', '/app/assessments'],
  },
  {
    name: 'dashboard-settings',
    path: '/dashboard/settings',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'DashboardSettingsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/settings/account', '/parametres'],
  },
  {
    name: 'brain-viewer',
    path: '/app/brain-viewer',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'BrainViewerPage',
    guard: true,
    requireAuth: true,
    status: 'beta',
    hidden: true,
  },
  {
    name: 'music',
    path: '/app/music',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CMusicEnhancedPage',
    guard: true,
    requireAuth: true,
    aliases: ['/music'],
  },
  {
    name: 'music-analytics',
    path: '/app/music/analytics',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'MusicAnalyticsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'music-profile',
    path: '/app/music/profile',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'MusicProfilePage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'music-collab',
    path: '/app/music/collab/:playlistId',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'CollaborativePlaylistPage',
    guard: false,
    requireAuth: false,
  },
  // emotion-music supprimé - utiliser /app/music
  // emotion-music-library supprimé - utiliser /app/music
  {
    name: 'music-premium',
    path: '/app/music-premium',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CMusicTherapyPremiumPage',
    guard: true,
    aliases: ['/music-therapy-premium'],
  },
  // Route supprimée - fonctionnalité intégrée dans B2CMusicEnhanced
  // music-library supprimé - fonctionnalité dans B2CMusicEnhanced
  {
    name: 'coach',
    path: '/app/coach',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CAICoachPage',
    guard: true,
    aliases: ['/coach'],
  },
  {
    name: 'coach-programs',
    path: '/app/coach/programs',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'CoachProgramsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'coach-program-detail',
    path: '/app/coach/programs/:programId',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'CoachProgramDetailPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'coach-sessions',
    path: '/app/coach/sessions',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'CoachSessionsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'coach-analytics',
    path: '/app/coach/analytics',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'CoachAnalyticsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'coach-micro',
    path: '/app/coach-micro',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CAICoachMicroPage',
    guard: true,
    aliases: ['/coach-micro-decisions'],
  },
  {
    name: 'journal',
    path: '/app/journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CJournalPage',
    guard: true,
    aliases: ['/journal'],
  },
  {
    name: 'emotion-sessions',
    path: '/app/emotion-sessions',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'EmotionSessionHistoryPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'emotion-sessions-new',
    path: '/app/emotion-sessions/new',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'EmotionSessionNewPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'journal-new',
    path: '/app/journal-new',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalNewPage',
    guard: true,
    requireAuth: true,
    aliases: ['/journal/new'],
  },
  {
    name: 'journal-activity',
    path: '/app/journal/activity',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalActivityPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'journal-analytics',
    path: '/app/journal/analytics',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalAnalyticsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'journal-archive',
    path: '/app/journal/archive',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalArchivePage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'journal-favorites',
    path: '/app/journal/favorites',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalFavoritesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'journal-goals',
    path: '/app/journal/goals',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalGoalsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'journal-notes',
    path: '/app/journal/notes',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalNotesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'journal-search',
    path: '/app/journal/search',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalSearchPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'weekly-bars',
    path: '/app/weekly-bars',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CWeeklyBarsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/weekly-bars', '/bars'],
  },
  {
    name: 'vr',
    path: '/app/vr',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'VRPage',
    guard: true,
    requireAuth: true,
    aliases: ['/vr'],
  },
  {
    name: 'vr-galaxy',
    path: '/app/vr-galaxy',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CVRGalaxyPage',
    guard: true,
    requireAuth: true,
    aliases: ['/vr-galaxy'],
  },
  {
    name: 'vr-breath-guide',
    path: '/app/vr-breath-guide',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'B2CVRBreathGuidePage',
    guard: true,
    requireAuth: true,
    aliases: ['/vr-breath'],
  },
  // ═══════════════════════════════════════════════════════════
  // B2C INTEGRATION - PARTICULIER ROUTES
  // ═══════════════════════════════════════════════════════════
  // Routes deprecated supprimées : mode-selection, b2c-dashboard, b2c-mood
  // Redirections gérées dans aliases.tsx
  {
    name: 'advanced-analytics',
    path: '/app/analytics/advanced',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'AdvancedAnalyticsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'meditation',
    path: '/app/meditation',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'MeditationPage',
    guard: true,
    requireAuth: true,
    aliases: ['/meditation'],
  },
  {
    name: 'nyvee-cocon',
    path: '/app/nyvee',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'BreathHubPage',
    guard: true,
    requireAuth: true,
    deprecated: true,
    redirectTo: '/app/breath-hub?mode=nuit',
  },
  {
    name: 'face-ar',
    path: '/app/face-ar',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CARFiltersPage',
    guard: true,
    aliases: ['/ar-filters'],
  },
  {
    name: 'seuil',
    path: '/app/seuil',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'SeuilPage',
    guard: true,
    requireAuth: true,
    aliases: ['/seuil', '/threshold'],
  },
  // Voice Journal - Journal vocal avec transcription
  {
    name: 'voice-journal',
    path: '/app/voice-journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CVoiceJournalPage',
    guard: true,
    aliases: ['/voice-journal', '/vocal-journal'],
  },
  // Route /app/emotions supprimée - alias vers /app/scan
  // ═══════════════════════════════════════════════════════════
  // MODULE ENTRAIDE UNIFIÉ (consolide Community, Groups, Buddies, Guilds, Social Cocon)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'entraide',
    path: '/app/entraide',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'EntraidePage',
    guard: true,
    requireAuth: true,
    aliases: ['/community', '/community-groups', '/groups', '/buddies-hub', '/social', '/entraide'],
  },
  // community-legacy supprimé — redirection dans aliases.tsx
  // ═══════════════════════════════════════════════════════════
  // EXCHANGE HUB V2.0 - 4 Marchés
  // ═══════════════════════════════════════════════════════════
  {
    name: 'exchange-hub',
    path: '/app/exchange',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ExchangeHubPage',
    guard: true,
    requireAuth: true,
    aliases: ['/exchange'],
    status: 'beta',
  },
  {
    name: 'buddies',
    path: '/app/buddies',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'BuddiesPage',
    guard: true,
    requireAuth: true,
    aliases: ['/buddy-system', '/find-buddy'],
  },
  {
    name: 'wearables',
    path: '/app/wearables',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'WearablesPage',
    guard: true,
    requireAuth: true,
    aliases: ['/health-sync', '/devices'],
    status: 'beta',
  },
  {
    name: 'context-lens',
    path: '/app/context-lens',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ContextLensPage',
    guard: true,
    requireAuth: true,
    aliases: ['/insights', '/patterns'],
    status: 'beta',
  },
  {
    name: 'data-export',
    path: '/app/data-export',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'DataExportPage',
    guard: true,
    requireAuth: true,
    aliases: ['/export-data', '/rgpd-export'],
  },
  {
    name: 'screen-silk',
    path: '/app/screen-silk',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CScreenSilkBreakPage',
    guard: true,
    aliases: ['/screen-silk-break'],
  },
  // Routes VR déjà définies aux lignes 676-686 et 666-675
  // Doublons supprimés pour éviter conflits
  {
    name: 'boss-grit',
    path: '/app/boss-grit',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CBossLevelGritPage',
    guard: true,
    aliases: ['/boss-level-grit'],
  },
  {
    name: 'mood-mixer',
    path: '/app/mood-mixer',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'MusicHubPage',
    guard: true,
    deprecated: true,
    redirectTo: '/app/music-hub?tab=mixer',
    aliases: ['/mood-mixer'],
  },
  {
    name: 'mood-presets-admin',
    path: '/app/mood-presets',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'MoodPresetsAdminPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'ambition-arcade',
    path: '/app/ambition-arcade',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CAmbitionArcadePage',
    guard: true,
    aliases: ['/ambition-arcade'],
  },
  {
    name: 'bounce-back',
    path: '/app/bounce-back',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CBounceBackBattlePage',
    guard: true,
    aliases: ['/bounce-back-battle'],
  },
  {
    name: 'story-synth',
    path: '/app/story-synth',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CStorySynthLabPage',
    guard: true,
    aliases: ['/story-synth-lab'],
  },
  {
    name: 'group-sessions',
    path: '/app/group-sessions',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GroupSessionsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/group-sessions', '/sessions-groupe'],
  },
  // social-cocon-b2c et communaute-b2c supprimés — redirections dans aliases.tsx
  // ═══════════════════════════════════════════════════════════
  // PARC ÉMOTIONNEL (NAVIGATION & IMMERSION)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'emotional-park',
    path: '/app/emotional-park',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'EmotionalParkPage',
    guard: true,
    aliases: ['/parc', '/park'],
  },
  {
    name: 'park-journey',
    path: '/app/park-journey',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ParkJourneyPage',
    guard: true,
    aliases: ['/voyage', '/journey'],
  },
  {
    name: 'emotion-atlas',
    path: '/app/emotion-atlas',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'EmotionAtlasPage',
    guard: true,
    aliases: ['/atlas', '/emotion-map'],
  },
  {
    name: 'discovery',
    path: '/app/discovery',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'DiscoveryPage',
    guard: true,
    aliases: ['/discovery', '/exploration'],
  },
  // ═══════════════════════════════════════════════════════════
  // ANALYTICS & DATA (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'analytics',
    path: '/app/analytics',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'AnalyticsPage',
    guard: true,
    aliases: ['/analytics'],
  },
  {
    name: 'leaderboard',
    path: '/app/leaderboard',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'LeaderboardPage',
    guard: true,
    aliases: ['/leaderboard'],
  },
  {
    name: 'gamification',
    path: '/gamification',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CGamificationPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'heatmap',
    path: '/app/scores',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ScoresPage',
    guard: true,
    aliases: ['/app/heatmap', '/heatmap-vibes'],
  },
  // Routes supplémentaires
  // coach-chat supprimé - utiliser /app/coach
  // vr-sessions supprimé - fonctionnalité dans B2CVRBreathGuidePage
  {
    name: 'sessions',
    path: '/app/sessions',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'SessionsPage',
    guard: true,
    aliases: ['/session', '/sessions'],
  },
  {
    name: 'session-detail',
    path: '/app/sessions/:id',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'SessionDetailPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'goals',
    path: '/app/goals',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GoalsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'goal-detail',
    path: '/app/goals/:id',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GoalDetailPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'goal-new',
    path: '/app/goals/new',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GoalNewPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'park-achievements',
    path: '/app/park/achievements',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'AchievementsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'daily-challenges',
    path: '/app/daily-challenges',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'DailyChallengesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'badges',
    path: '/app/badges',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'BadgesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'rewards',
    path: '/app/rewards',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'RewardsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'challenges',
    path: '/app/challenges',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ChallengesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'challenge-detail',
    path: '/app/challenges/:id',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ChallengeDetailPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'challenge-create',
    path: '/app/challenges/create',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ChallengeCreatePage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'notifications-center',
    path: '/app/notifications',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'NotificationsCenterPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'notification-settings',
    path: '/settings/notifications',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CNotificationsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/notifications'],
  },
  {
    name: 'premium',
    path: '/app/premium',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'PremiumPage',
    guard: true,
    requireAuth: true,
    aliases: ['/premium'],
  },
  {
    name: 'billing',
    path: '/app/billing',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'BillingPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'support',
    path: '/app/support',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'SupportPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'tickets',
    path: '/app/tickets',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'TicketsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'insights',
    path: '/app/insights',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'InsightsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'trends',
    path: '/app/trends',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'TrendsPage',
    guard: true,
    requireAuth: true,
  },
  // ═══════════════════════════════════════════════════════════
  // PAGES EXISTANTES NON MAPPÉES (CONSOLIDATION)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'messages',
    path: '/messages',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'MessagesPage',
    guard: true,
    aliases: ['/chat', '/nyvee-chat'],
  },
  {
    name: 'calendar',
    path: '/calendar',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'CalendarPage',
    guard: true,
    aliases: ['/agenda'],
  },
  {
    name: 'point20',
    path: '/point20',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'Point20Page',
    guard: true,
    aliases: ['/recuperation-20'],
  },
  // test-page supprimé — route dev-only
  // Routes legacy supprimées - redirection automatique via aliases dans les routes principales
  // emotions-legacy supprimé - utiliser /app/scan directement
  {
    name: 'reporting',
    path: '/reporting',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ReportingPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'export',
    path: '/export',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ExportPage',
    guard: true,
    requireAuth: true,
  },
  // modules-journal supprimé - utiliser /app/journal
  // ═══════════════════════════════════════════════════════════
  // PARAMÈTRES & COMPTE
  // ═══════════════════════════════════════════════════════════
  {
    name: 'settings-general',
    path: '/settings/general',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CSettingsPage',
    guard: true,
    aliases: ['/settings', '/preferences'],
  },
  {
    name: 'settings-profile',
    path: '/settings/profile',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CProfileSettingsPage',
    guard: true,
    aliases: ['/profile-settings'],
  },
  {
    name: 'settings-data',
    path: '/settings/data',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'DataSettingsPage',
    guard: true,
    aliases: ['/data-settings'],
  },
  {
    name: 'app-profile',
    path: '/app/profile',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CProfileSettingsPage',
    guard: true,
    aliases: ['/profile'],
  },
  {
    name: 'settings-privacy',
    path: '/settings/privacy',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CPrivacyTogglesPage',
    guard: true,
    aliases: ['/privacy-toggles', '/settings/data-privacy'],
  },
  {
    name: 'how-it-adapts',
    path: '/app/how-it-adapts',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'HowItAdaptsPage',
    guard: true,
    requireAuth: true,
  },
  // settings-notifications supprimé - doublon de notification-settings (même path /settings/notifications)
  // Fonctionnalité gérée par NotificationSettingsPage via notification-settings
  {
    name: 'settings-journal',
    path: '/settings/journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalSettingsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'settings-accessibility',
    path: '/settings/accessibility',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'AccessibilitySettingsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'settings-language',
    path: '/settings/language',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'LanguageSettingsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'settings-security',
    path: '/settings/security',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'SecuritySettingsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'challenges-history',
    path: '/app/challenges/history',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'ChallengesHistoryPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'achievements',
    path: '/app/achievements',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'AchievementsPage',
    guard: true,
    requireAuth: true,
  },
  // ═══════════════════════════════════════════════════════════
  // TOOLS & NAVIGATION PAGES
  // ═══════════════════════════════════════════════════════════
  // Routes supprimées (pages orphelines nettoyées)
  // - NavigationPage (supprimée)
  // - CompleteFeatureMatrix (supprimée)
  // - MissingPagesManifest (supprimée)
  // ═══════════════════════════════════════════════════════════
  // DÉVELOPPEMENT (UNIQUEMENT SI DEBUG)
  // ═══════════════════════════════════════════════════════════
  ...(import.meta.env.MODE === 'development' ? ([
    {
      name: 'validation',
      path: '/validation',
      segment: 'public',
      layout: 'simple',
      component: 'ValidationPage',
      guard: false,
    }
  ] as RouteMeta[]) : []),
  // ═══════════════════════════════════════════════════════════
  // DEV-ONLY ROUTES (Masquées en production)
  // ═══════════════════════════════════════════════════════════
  // Routes de développement masquées en production
  ...(import.meta.env.DEV ? ([
    {
      name: 'comprehensive-system-audit',
      path: '/dev/system-audit',
      segment: 'public',
      layout: 'marketing',
      component: 'ComprehensiveSystemAuditPage',
      guard: false,
    },
    {
      name: 'security-audit-scorecard',
      path: '/admin/security-scorecard',
      segment: 'public',
      layout: 'marketing',
      component: 'SecurityAuditScorecard',
      guard: false,
    },
    {
      name: 'security-dossier-b2b',
      path: '/admin/security-dossier',
      segment: 'public',
      layout: 'marketing',
      component: 'SecurityDossierB2B',
      guard: false,
    },
    {
      name: 'seo-audit',
      path: '/admin/seo-audit',
      segment: 'public',
      layout: 'marketing',
      component: 'SEOAuditPage',
      guard: false,
    },
    {
      name: 'error-boundary-test',
      path: '/dev/error-boundary',
      segment: 'public',
      layout: 'marketing',
      component: 'ErrorBoundaryTestPage',
      guard: false,
    },
  // Routes de debug supprimées (pages orphelines nettoyées)
  // - DiagnosticPage (supprimée)
  // - SystemValidationPage (supprimée) 
  // - SystemRepairPage (supprimée)
  ] as RouteMeta[]) : []),
  // ═══════════════════════════════════════════════════════════
  // LEGAL & COMPLIANCE PAGES - Déjà défini aux lignes 91-136
  // ═══════════════════════════════════════════════════════════
  // ═══════════════════════════════════════════════════════════
  // BILLING & SUBSCRIPTION
  // ═══════════════════════════════════════════════════════════
  {
    name: 'subscribe',
    path: '/subscribe',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'SubscribePage',
    guard: true,
    requireAuth: true,
    aliases: ['/billing', '/plans'],
  },
  // ═══════════════════════════════════════════════════════════
  // NOUVELLES ROUTES - COMPLEMENTAIRES
  // ═══════════════════════════════════════════════════════════
  // Routes deprecated supprimées : voice-analysis, friends, groups, feed
  // Redirections gérées dans aliases.tsx
  // Personnalisation
  {
    name: 'themes',
    path: '/app/themes',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ThemesPage',
    guard: true,
    status: 'beta',
  },
  {
    name: 'customization',
    path: '/app/customization',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'CustomizationPage',
    guard: true,
    status: 'beta',
  },
  {
    name: 'widgets',
    path: '/app/widgets',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'WidgetsPage',
    guard: true,
    status: 'beta',
  },
  // Événements & Ateliers
  {
    name: 'events-calendar',
    path: '/app/events/calendar',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'EventsCalendarPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'workshops',
    path: '/app/workshops',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'WorkshopsPage',
    guard: true,
    status: 'beta',
  },
  {
    name: 'webinars',
    path: '/app/webinars',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'WebinarsPage',
    guard: true,
    status: 'beta',
  },
  // Export & Partage
  {
    name: 'export-pdf',
    path: '/app/export/pdf',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ExportPDFPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'export-csv',
    path: '/app/export/csv',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ExportCSVPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'share-data',
    path: '/app/share',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ShareDataPage',
    guard: true,
    requireAuth: true,
  },
  // Intégrations
  {
    name: 'integrations',
    path: '/app/integrations',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'IntegrationsPage',
    guard: true,
    status: 'beta',
  },
  // api-keys et webhooks supprimés — routes dev-only
  // Accessibilité
  {
    name: 'accessibility-settings',
    path: '/app/accessibility-settings',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'AccessibilitySettingsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'shortcuts',
    path: '/app/shortcuts',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ShortcutsPage',
    guard: true,
    requireAuth: true,
  },
  // Rapports
  {
    name: 'weekly-report',
    path: '/app/reports/weekly',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'WeeklyReportPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'monthly-report',
    path: '/app/reports/monthly',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'MonthlyReportPage',
    guard: true,
    requireAuth: true,
  },
  // Navigation Hub - DOUBLON SUPPRIMÉ (défini ligne 781)
  // Gamification avancée
  {
    name: 'guilds',
    path: '/app/guilds',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GuildListPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'guild-detail',
    path: '/app/guilds/:guildId',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GuildPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'premium-rewards',
    path: '/app/rewards/premium',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'PremiumRewardsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'tournaments',
    path: '/app/tournaments',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'TournamentsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'match-spectator',
    path: '/app/match/:matchId/spectate',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'MatchSpectatorPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'competitive-seasons',
    path: '/app/competitive-seasons',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'CompetitiveSeasonsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'app-support-chatbot',
    path: '/app/support/chatbot',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'SupportChatbotPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'app-unified-dashboard',
    path: '/app/unified',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'UnifiedDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'app-immersive',
    path: '/app/immersive',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CImmersivePage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'app-activity-logs',
    path: '/app/activity-logs',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ActivityLogsPage',
    guard: true,
    requireAuth: true,
  },
  // ═══════════════════════════════════════════════════════════
  // SYSTEM & MONITORING
  // ═══════════════════════════════════════════════════════════
  // system-health et k6-analytics supprimés — routes dev-only
  // ═══════════════════════════════════════════════════════════
  // ROUTES MANQUANTES - AJOUTÉES POUR COHÉRENCE
  // ═══════════════════════════════════════════════════════════
  {
    name: 'hume-ai-realtime',
    path: '/app/hume-ai',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'HumeAIRealtimePage',
    guard: true,
    requireAuth: true,
    aliases: ['/hume-ai', '/emotion-ai'],
    status: 'coming-soon',
  },
  {
    name: 'suno-music-generator',
    path: '/app/suno',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'SunoMusicGeneratorPage',
    guard: true,
    requireAuth: true,
    aliases: ['/suno', '/ai-music-generator'],
    status: 'beta',
  },
  // auras-leaderboard supprimé — redirection dans aliases.tsx
  {
    name: 'consent-management',
    path: '/app/consent',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ConsentManagementPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'account-deletion',
    path: '/app/delete-account',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'AccountDeletionPage',
    guard: true,
    requireAuth: true,
  },
  // ═══════════════════════════════════════════════════════════
  // MODULE 31 - Visioconférence bien-être
  // ═══════════════════════════════════════════════════════════
  {
    name: 'visio',
    path: '/app/visio',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2BVisioPage',
    guard: true,
    requireAuth: true,
    aliases: ['/visio', '/visioconference'],
  },
  // ═══════════════════════════════════════════════════════════
  // MODULE 38 - Burnout Assessment (MBI-HSS)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'burnout-assessment',
    path: '/app/assess/burnout',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'BurnoutAssessmentPage',
    guard: true,
    requireAuth: true,
    aliases: ['/assess/burnout', '/burnout'],
    status: 'demo',
  },
] as const;
