// @ts-nocheck
import type { RouteMeta } from '../schema';

export const PUBLIC_ROUTES: readonly RouteMeta[] = [
  // ═══════════════════════════════════════════════════════════
  // ROUTES PUBLIQUES
  // ═══════════════════════════════════════════════════════════
  {
    name: 'home',
    path: '/',
    segment: 'public',
    layout: 'simple', // Homepage has its own header/footer in AppleHomePage
    component: 'HomePage',
    guard: false, // Pas de guard - accessible à tous
  },
  {
    name: 'pricing',
    path: '/pricing',
    segment: 'public',
    layout: 'marketing',
    component: 'PricingPageWorkingPage',
    guard: false,
    aliases: ['/tarifs'],
  },
  // /home redirect supprimé - confus et inutile
  {
    name: 'about',
    path: '/about',
    segment: 'public',
    layout: 'marketing',
    component: 'AboutPage',
    guard: false,
    aliases: ['/a-propos'],
  },
  {
    name: 'contact',
    path: '/contact',
    segment: 'public',
    layout: 'marketing',
    component: 'ContactPage',
    guard: false,
  },
  {
    name: 'help',
    path: '/help',
    segment: 'public',
    layout: 'marketing',
    component: 'HelpPage',
    guard: false,
  },
  {
    name: 'faq',
    path: '/faq',
    segment: 'public',
    layout: 'marketing',
    component: 'FAQPage',
    guard: false,
  },
  {
    name: 'use-cases',
    path: '/use-cases',
    segment: 'public',
    layout: 'marketing',
    component: 'UseCasesPage',
    guard: false,
    aliases: ['/cas-usage'],
  },
  {
    name: 'security',
    path: '/security',
    segment: 'public',
    layout: 'marketing',
    component: 'SecurityPage',
    guard: false,
    aliases: ['/securite'],
  },
  {
    name: 'store',
    path: '/store',
    segment: 'public',
    layout: 'marketing',
    component: 'StorePage',
    guard: false,
  },
  {
    name: 'product-detail',
    path: '/store/product/:handle',
    segment: 'public',
    layout: 'marketing',
    component: 'ProductDetailPage',
    guard: false,
  },
  {
    name: 'features',
    path: '/features',
    segment: 'public',
    layout: 'marketing',
    component: 'FeaturesPage',
    guard: false,
    aliases: ['/fonctionnalites'],
  },
  {
    name: 'scanner-emotionnel',
    path: '/scanner',
    segment: 'public',
    layout: 'marketing',
    component: 'ScannerEmotionnelPage',
    guard: false,
    aliases: ['/scanner-emotionnel'],
  },
  {
    name: 'demo',
    path: '/demo',
    segment: 'public',
    layout: 'marketing',
    component: 'DemoPage',
    guard: false,
  },
  {
    name: 'onboarding',
    path: '/onboarding',
    segment: 'public',
    layout: 'marketing',
    component: 'OnboardingPage',
    guard: false,
  },
  {
    name: 'install',
    path: '/install',
    segment: 'public',
    layout: 'marketing',
    component: 'InstallPage',
    guard: false,
  },
  {
    name: 'marketplace',
    path: '/marketplace',
    segment: 'public',
    layout: 'marketing',
    component: 'MarketplacePage',
    guard: false,
  },
  {
    name: 'privacy',
    path: '/privacy',
    segment: 'public',
    layout: 'marketing',
    component: 'PrivacyPage',
    aliases: ['/politique-confidentialite'],
    guard: false,
  },
  {
    name: 'legal-mentions',
    path: '/legal/mentions',
    segment: 'public',
    layout: 'marketing',
    component: 'MentionsLegalesPage',
    guard: false,
    aliases: ['/mentions-legales'],
  },
  {
    name: 'legal-privacy',
    path: '/legal/privacy',
    segment: 'public',
    layout: 'marketing',
    component: 'PrivacyPolicyPage',
    guard: false,
  },
  {
    name: 'legal-terms',
    path: '/legal/terms',
    segment: 'public',
    layout: 'marketing',
    component: 'TermsPage',
    guard: false,
    aliases: ['/cgu'],
  },
  {
    name: 'legal-sales',
    path: '/legal/sales',
    segment: 'public',
    layout: 'marketing',
    component: 'SalesTermsPage',
    guard: false,
    aliases: ['/cgv'],
  },
  {
    name: 'legal-cookies',
    path: '/legal/cookies',
    segment: 'public',
    layout: 'marketing',
    component: 'CookiesPage',
    guard: false,
    aliases: ['/cookies'],
  },
  {
    name: 'legal-licenses',
    path: '/legal/licenses',
    segment: 'public',
    layout: 'marketing',
    component: 'LicensesPage',
    guard: false,
  },
  {
    name: 'b2c-landing',
    path: '/b2c',
    segment: 'public',
    layout: 'marketing',
    component: 'HomeB2CPage',
    guard: false,
  },
  {
    name: 'b2b-landing',
    path: '/entreprise',
    segment: 'public',
    layout: 'marketing',
    component: 'B2BEntreprisePage',
    aliases: ['/b2b', '/b2b/landing', '/b2b/institutional'],
    guard: false,
  },
  // Route /b2b/landing supprimée - alias dans b2b-landing
  {
    name: 'b2b-selection',
    path: '/b2b/selection',
    segment: 'public',
    layout: 'simple',
    guard: false,
    component: 'B2BSelectionPage',
  },
  // ═══════════════════════════════════════════════════════════
  // B2B INSTITUTIONAL (nouvelles routes)
  // ═══════════════════════════════════════════════════════════
  // /b2b/institutional supprimé — redondant avec /b2b. Alias dans b2b-landing.
  {
    name: 'b2b-institutional-access',
    path: '/b2b/access',
    segment: 'public',
    layout: 'marketing',
    component: 'InstitutionalAccessPage',
    guard: false,
  },
  {
    name: 'b2b-wellness-hub',
    path: '/b2b/wellness',
    segment: 'public',
    layout: 'app',
    component: 'WellnessHubPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'b2b-module-wrapper',
    path: '/b2b/module/:moduleId',
    segment: 'public',
    layout: 'simple',
    component: 'B2BModuleWrapperPage',
    guard: false,
  },
  {
    name: 'login',
    path: '/login',
    segment: 'public',
    layout: 'marketing',
    component: 'UnifiedLoginPage',
    aliases: ['/auth', '/auth/login', '/b2c/login', '/b2b/user/login', '/b2b/admin/login'],
    guard: false,
  },
  {
    name: 'signup',
    path: '/signup',
    segment: 'public',
    layout: 'marketing',
    component: 'SignupPage',
    aliases: ['/register', '/b2c/register', '/b2b/user/register'],
    guard: false,
  },
  {
    name: 'reset-password',
    path: '/reset-password',
    segment: 'public',
    layout: 'marketing',
    component: 'ResetPasswordPage',
    aliases: ['/auth/reset-password'],
    guard: false,
  },
  {
    name: 'exam-mode',
    path: '/exam-mode',
    segment: 'public',
    layout: 'marketing',
    component: 'ExamModePage',
    guard: false, // SSO géré dans le composant
    aliases: ['/mode/exams', '/examens'],
  },
  {
    name: 'parcours-xl',
    path: '/app/parcours-xl',
    segment: 'public',
    layout: 'simple',
    component: 'ParcoursXLPage',
    guard: false,
    aliases: ['/parcours-xl'],
  },
  // b2c-music supprimé - utiliser /app/music avec B2CMusicEnhanced
  // ═══════════════════════════════════════════════════════════
  // MODULES FUN-FIRST (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'flash-glow',
    path: '/app/flash-glow',
    segment: 'public',
    layout: 'simple',
    component: 'B2CFlashGlowPage',
    guard: false,
    aliases: ['/flash-glow', '/instant-glow', '/b2c-flash-glow', '/flash-glow-advanced'],
  },
  {
    name: 'breath',
    path: '/app/breath',
    segment: 'public',
    layout: 'simple',
    component: 'B2CBreathworkPage',
    guard: false,
    aliases: ['/breathwork', '/breathwork-adaptive'],
  },
  // nyvee-test et test-accounts-dev supprimés — routes dev-only gérées directement dans router.tsx
  {
    name: 'navigation-hub',
    path: '/navigation',
    segment: 'public',
    layout: 'simple',
    component: 'NavigationPage',
    guard: false,
    aliases: ['/all-pages', '/sitemap'],
  },
  {
    name: 'bubble-beat',
    path: '/app/bubble-beat',
    segment: 'public',
    layout: 'simple',
    component: 'BreathHubPage',
    guard: false,
    deprecated: true,
    redirectTo: '/app/breath-hub?mode=gamifie',
    aliases: ['/bubble-beat'],
  },
  {
    name: 'activity',
    path: '/app/activity',
    segment: 'public',
    layout: 'simple',
    component: 'B2CActivitePage',
    guard: false,
    aliases: ['/activity-history'],
  },
  {
    name: 'payment-success',
    path: '/payment-success',
    segment: 'public',
    layout: 'marketing',
    component: 'PaymentSuccessPage',
    guard: false,
  },
  {
    name: 'app-faq',
    path: '/app/faq',
    segment: 'public',
    layout: 'simple',
    component: 'FAQPage',
    guard: false,
  },
  // ═══════════════════════════════════════════════════════════
  // PAGES SYSTÈME
  // ═══════════════════════════════════════════════════════════
  {
    name: 'unauthorized',
    path: '/401',
    segment: 'public',
    layout: 'marketing',
    component: 'UnauthorizedPage',
    guard: false,
  },
  {
    name: 'forbidden',
    path: '/403',
    segment: 'public',
    layout: 'marketing',
    component: 'ForbiddenPage',
    guard: false,
  },
  {
    name: 'not-found',
    path: '/404',
    segment: 'public',
    layout: 'marketing',
    component: 'UnifiedErrorPage',
    guard: false,
  },
  {
    name: 'server-error',
    path: '/500',
    segment: 'public',
    layout: 'marketing',
    component: 'ServerErrorPage',
    guard: false,
  },
  {
    name: 'unified-home',
    path: '/unified-home',
    segment: 'public',
    layout: 'simple',
    component: 'UnifiedHomePage',
    guard: false,
  },
  // ═══════════════════════════════════════════════════════════
  // MODULE 37 - Sécurité des données de santé
  // ═══════════════════════════════════════════════════════════
  {
    name: 'securite-sante',
    path: '/compliance/securite-sante',
    segment: 'public',
    layout: 'marketing',
    component: 'HDSCompliancePage',
    guard: false,
    aliases: ['/compliance/hds', '/hds', '/conformite-hds'],
  },
] as const;
