# Yarn configuration to avoid problematic packages
nodeLinker: node-modules

# Skip problematic optional dependencies  
enableImmutableCache: false

# Ignore specific problematic packages
ignoreDependencies:
  - imagemin-avif
  - imagemin-webp
  - vite-plugin-imagemin
  - jpegtran-bin
  - imagemin-jpegtran