/**
 * Thèmes prédéfinis
 * Phase 3 - Excellence
 */

import type { ThemePreset } from '@/types/themes';

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'default-light',
    name: 'EmotionsCare Light',
    description: 'Thème clair par défaut, apaisant et professionnel',
    category: 'default',
    isPremium: false,
    tags: ['default', 'light', 'professional'],
    thumbnail: '/themes/default-light.png',
    theme: {
      name: 'EmotionsCare Light',
      mode: 'light',
      isBuiltIn: true,
      isPremium: false,
      colors: {
        primary: '221.2 83.2% 53.3%',
        'primary-foreground': '210 40% 98%',
        secondary: '210 40% 96.1%',
        'secondary-foreground': '222.2 47.4% 11.2%',
        accent: '210 40% 96.1%',
        'accent-foreground': '222.2 47.4% 11.2%',
        background: '0 0% 100%',
        foreground: '222.2 84% 4.9%',
        card: '0 0% 100%',
        'card-foreground': '222.2 84% 4.9%',
        popover: '0 0% 100%',
        'popover-foreground': '222.2 84% 4.9%',
        muted: '210 40% 96.1%',
        'muted-foreground': '215.4 16.3% 46.9%',
        destructive: '0 84.2% 60.2%',
        'destructive-foreground': '210 40% 98%',
        success: '142.1 76.2% 36.3%',
        'success-foreground': '355.7 100% 97.3%',
        warning: '38 92% 50%',
        'warning-foreground': '48 96% 89%',
        info: '199 89% 48%',
        'info-foreground': '210 40% 98%',
        border: '214.3 31.8% 91.4%',
        input: '214.3 31.8% 91.4%',
        ring: '221.2 83.2% 53.3%',
        'chart-1': '221.2 83.2% 53.3%',
        'chart-2': '142.1 76.2% 36.3%',
        'chart-3': '38 92% 50%',
        'chart-4': '280 65% 60%',
        'chart-5': '340 82% 52%',
      },
      fonts: {
        heading: 'Inter, system-ui, sans-serif',
        body: 'Inter, system-ui, sans-serif',
        mono: 'Fira Code, monospace',
      },
      spacing: {
        scale: 1,
        radius: 'md',
      },
      effects: {
        blur: 'md',
        shadows: 'md',
        animations: true,
        reducedMotion: false,
      },
      accessibility: {
        highContrast: false,
        focusIndicatorStyle: 'ring',
        fontSize: 'base',
        lineHeight: 'normal',
      },
    },
  },
  {
    id: 'default-dark',
    name: 'EmotionsCare Dark',
    description: 'Thème sombre élégant pour réduire la fatigue oculaire',
    category: 'default',
    isPremium: false,
    tags: ['default', 'dark', 'comfortable'],
    thumbnail: '/themes/default-dark.png',
    theme: {
      name: 'EmotionsCare Dark',
      mode: 'dark',
      isBuiltIn: true,
      isPremium: false,
      colors: {
        primary: '217.2 91.2% 59.8%',
        'primary-foreground': '222.2 47.4% 11.2%',
        secondary: '217.2 32.6% 17.5%',
        'secondary-foreground': '210 40% 98%',
        accent: '217.2 32.6% 17.5%',
        'accent-foreground': '210 40% 98%',
        background: '222.2 84% 4.9%',
        foreground: '210 40% 98%',
        card: '222.2 84% 4.9%',
        'card-foreground': '210 40% 98%',
        popover: '222.2 84% 4.9%',
        'popover-foreground': '210 40% 98%',
        muted: '217.2 32.6% 17.5%',
        'muted-foreground': '215 20.2% 65.1%',
        destructive: '0 62.8% 30.6%',
        'destructive-foreground': '210 40% 98%',
        success: '142.1 70.6% 45.3%',
        'success-foreground': '144.9 80.4% 10%',
        warning: '38 92% 50%',
        'warning-foreground': '48 96% 89%',
        info: '199 89% 48%',
        'info-foreground': '210 40% 98%',
        border: '217.2 32.6% 17.5%',
        input: '217.2 32.6% 17.5%',
        ring: '224.3 76.3% 48%',
        'chart-1': '220 70% 50%',
        'chart-2': '160 60% 45%',
        'chart-3': '30 80% 55%',
        'chart-4': '280 65% 60%',
        'chart-5': '340 75% 55%',
      },
      fonts: {
        heading: 'Inter, system-ui, sans-serif',
        body: 'Inter, system-ui, sans-serif',
        mono: 'Fira Code, monospace',
      },
      spacing: {
        scale: 1,
        radius: 'md',
      },
      effects: {
        blur: 'md',
        shadows: 'lg',
        animations: true,
        reducedMotion: false,
      },
      accessibility: {
        highContrast: false,
        focusIndicatorStyle: 'ring',
        fontSize: 'base',
        lineHeight: 'normal',
      },
    },
  },
  {
    id: 'high-contrast',
    name: 'Haut Contraste',
    description: 'Thème optimisé pour l\'accessibilité avec un contraste maximal',
    category: 'accessibility',
    isPremium: false,
    tags: ['accessibility', 'high-contrast', 'wcag-aaa'],
    thumbnail: '/themes/high-contrast.png',
    theme: {
      name: 'Haut Contraste',
      mode: 'light',
      isBuiltIn: true,
      isPremium: false,
      colors: {
        primary: '0 0% 0%',
        'primary-foreground': '0 0% 100%',
        secondary: '0 0% 20%',
        'secondary-foreground': '0 0% 100%',
        accent: '0 0% 20%',
        'accent-foreground': '0 0% 100%',
        background: '0 0% 100%',
        foreground: '0 0% 0%',
        card: '0 0% 100%',
        'card-foreground': '0 0% 0%',
        popover: '0 0% 100%',
        'popover-foreground': '0 0% 0%',
        muted: '0 0% 90%',
        'muted-foreground': '0 0% 0%',
        destructive: '0 100% 30%',
        'destructive-foreground': '0 0% 100%',
        success: '120 100% 20%',
        'success-foreground': '0 0% 100%',
        warning: '45 100% 25%',
        'warning-foreground': '0 0% 100%',
        info: '210 100% 25%',
        'info-foreground': '0 0% 100%',
        border: '0 0% 0%',
        input: '0 0% 0%',
        ring: '0 0% 0%',
        'chart-1': '0 0% 0%',
        'chart-2': '0 0% 30%',
        'chart-3': '0 0% 50%',
        'chart-4': '0 0% 70%',
        'chart-5': '0 0% 85%',
      },
      fonts: {
        heading: 'Arial, sans-serif',
        body: 'Arial, sans-serif',
        mono: 'Courier New, monospace',
      },
      spacing: {
        scale: 1.2,
        radius: 'none',
      },
      effects: {
        blur: 'none',
        shadows: 'none',
        animations: false,
        reducedMotion: true,
      },
      accessibility: {
        highContrast: true,
        focusIndicatorStyle: 'outline',
        fontSize: 'lg',
        lineHeight: 'relaxed',
      },
    },
  },
  {
    id: 'calm-ocean',
    name: 'Océan Calme',
    description: 'Palette apaisante inspirée de l\'océan',
    category: 'mood',
    isPremium: true,
    tags: ['premium', 'calm', 'ocean', 'relaxing'],
    thumbnail: '/themes/calm-ocean.png',
    theme: {
      name: 'Océan Calme',
      mode: 'light',
      isBuiltIn: true,
      isPremium: true,
      colors: {
        primary: '199 89% 48%',
        'primary-foreground': '0 0% 100%',
        secondary: '187 71% 88%',
        'secondary-foreground': '199 18% 33%',
        accent: '174 72% 56%',
        'accent-foreground': '0 0% 100%',
        background: '180 100% 99%',
        foreground: '199 18% 20%',
        card: '0 0% 100%',
        'card-foreground': '199 18% 20%',
        popover: '0 0% 100%',
        'popover-foreground': '199 18% 20%',
        muted: '187 71% 95%',
        'muted-foreground': '199 18% 46%',
        destructive: '0 72% 51%',
        'destructive-foreground': '0 0% 100%',
        success: '152 69% 31%',
        'success-foreground': '0 0% 100%',
        warning: '35 91% 57%',
        'warning-foreground': '0 0% 100%',
        info: '199 89% 48%',
        'info-foreground': '0 0% 100%',
        border: '187 71% 88%',
        input: '187 71% 88%',
        ring: '199 89% 48%',
        'chart-1': '199 89% 48%',
        'chart-2': '174 72% 56%',
        'chart-3': '152 69% 31%',
        'chart-4': '187 71% 88%',
        'chart-5': '199 18% 46%',
      },
      fonts: {
        heading: 'Poppins, sans-serif',
        body: 'Inter, sans-serif',
        mono: 'Fira Code, monospace',
      },
      spacing: {
        scale: 1,
        radius: 'lg',
      },
      effects: {
        blur: 'lg',
        shadows: 'lg',
        animations: true,
        reducedMotion: false,
      },
      accessibility: {
        highContrast: false,
        focusIndicatorStyle: 'ring',
        fontSize: 'base',
        lineHeight: 'normal',
      },
    },
  },
  {
    id: 'forest-zen',
    name: 'Forêt Zen',
    description: 'Inspiré de la nature pour une sérénité optimale',
    category: 'mood',
    isPremium: true,
    tags: ['premium', 'nature', 'zen', 'green'],
    thumbnail: '/themes/forest-zen.png',
    theme: {
      name: 'Forêt Zen',
      mode: 'light',
      isBuiltIn: true,
      isPremium: true,
      colors: {
        primary: '142 71% 45%',
        'primary-foreground': '0 0% 100%',
        secondary: '84 24% 88%',
        'secondary-foreground': '84 20% 20%',
        accent: '142 71% 45%',
        'accent-foreground': '0 0% 100%',
        background: '60 9% 98%',
        foreground: '84 20% 15%',
        card: '0 0% 100%',
        'card-foreground': '84 20% 15%',
        popover: '0 0% 100%',
        'popover-foreground': '84 20% 15%',
        muted: '84 24% 92%',
        'muted-foreground': '84 10% 45%',
        destructive: '0 72% 51%',
        'destructive-foreground': '0 0% 100%',
        success: '142 71% 45%',
        'success-foreground': '0 0% 100%',
        warning: '35 91% 57%',
        'warning-foreground': '0 0% 100%',
        info: '199 89% 48%',
        'info-foreground': '0 0% 100%',
        border: '84 24% 88%',
        input: '84 24% 88%',
        ring: '142 71% 45%',
        'chart-1': '142 71% 45%',
        'chart-2': '84 60% 50%',
        'chart-3': '35 91% 57%',
        'chart-4': '199 89% 48%',
        'chart-5': '280 65% 60%',
      },
      fonts: {
        heading: 'Raleway, sans-serif',
        body: 'Lato, sans-serif',
        mono: 'Source Code Pro, monospace',
      },
      spacing: {
        scale: 1,
        radius: 'xl',
      },
      effects: {
        blur: 'md',
        shadows: 'md',
        animations: true,
        reducedMotion: false,
      },
      accessibility: {
        highContrast: false,
        focusIndicatorStyle: 'ring',
        fontSize: 'base',
        lineHeight: 'normal',
      },
    },
  },
  {
    id: 'sunset-warmth',
    name: 'Chaleur du Coucher de Soleil',
    description: 'Tons chauds et réconfortants',
    category: 'mood',
    isPremium: true,
    tags: ['premium', 'warm', 'sunset', 'cozy'],
    thumbnail: '/themes/sunset-warmth.png',
    theme: {
      name: 'Chaleur du Coucher de Soleil',
      mode: 'light',
      isBuiltIn: true,
      isPremium: true,
      colors: {
        primary: '14 90% 60%',
        'primary-foreground': '0 0% 100%',
        secondary: '35 90% 85%',
        'secondary-foreground': '14 50% 20%',
        accent: '340 82% 52%',
        'accent-foreground': '0 0% 100%',
        background: '30 50% 98%',
        foreground: '14 50% 15%',
        card: '0 0% 100%',
        'card-foreground': '14 50% 15%',
        popover: '0 0% 100%',
        'popover-foreground': '14 50% 15%',
        muted: '35 90% 92%',
        'muted-foreground': '14 30% 45%',
        destructive: '0 72% 51%',
        'destructive-foreground': '0 0% 100%',
        success: '142 71% 45%',
        'success-foreground': '0 0% 100%',
        warning: '35 91% 57%',
        'warning-foreground': '0 0% 100%',
        info: '199 89% 48%',
        'info-foreground': '0 0% 100%',
        border: '35 90% 85%',
        input: '35 90% 85%',
        ring: '14 90% 60%',
        'chart-1': '14 90% 60%',
        'chart-2': '340 82% 52%',
        'chart-3': '35 91% 57%',
        'chart-4': '280 65% 60%',
        'chart-5': '199 89% 48%',
      },
      fonts: {
        heading: 'Playfair Display, serif',
        body: 'Nunito, sans-serif',
        mono: 'JetBrains Mono, monospace',
      },
      spacing: {
        scale: 1.1,
        radius: 'lg',
      },
      effects: {
        blur: 'lg',
        shadows: 'xl',
        animations: true,
        reducedMotion: false,
      },
      accessibility: {
        highContrast: false,
        focusIndicatorStyle: 'ring',
        fontSize: 'base',
        lineHeight: 'relaxed',
      },
    },
  },
];
