openapi: 3.0.0
info:
  title: Admin API
  version: 1.0.0
paths:
  /admin/organization:
    get:
      summary: Get organization details
      responses:
        '200':
          description: Organization info
    put:
      summary: Update organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated organization
