preset_key: "universel-reset"
title: "Reset Universel → Équilibre"
emotion_category: "neutre"
duration_target: 20

music:
  bpm: 68
  mode: "dorien"
  progression: "vi–IV–I–V"
  meter: "6/8"
  instruments: "piano feutré + handpan + pads chauds"
  model: "V4_5"
  style_weight: 0.7
  weirdness: 0.2

segments:
  - title: "Respiration guidée"
    start_s: 0
    end_s: 120
    technique: "Cohérence cardiaque 6/min"
    voiceover: |
      Bienvenue. Installez-vous confortablement. Fermez les yeux si vous le souhaitez.
      Nous allons commencer par une respiration qui calme le système nerveux.
      Inspirez pendant 4 temps... Expirez pendant 6 temps...
      Suivez ce rythme naturel. Sentez votre corps se poser.
    
  - title: "Attention au présent"
    start_s: 120
    end_s: 240
    technique: "ATT (Attention Training Technique)"
    voiceover: |
      Maintenant, portez votre attention sur les sons autour de vous.
      Écoutez la musique qui vous entoure, comme une vague.
      Vous n'avez rien à faire, juste écouter.
      Votre esprit peut vagabonder, c'est normal. Revenez doucement à la musique.

  - title: "Défusion cognitive"
    start_s: 240
    end_s: 360
    technique: "ACT - Défusion"
    voiceover: |
      Si des pensées arrivent, imaginez-les comme des nuages dans le ciel.
      Vous n'êtes pas vos pensées. Vous êtes le ciel qui les regarde passer.
      Étiquetez simplement : "Voilà une pensée de..." et laissez-la flotter.

  - title: "Recadrage & Ancrage"
    start_s: 360
    end_s: 600
    technique: "Restructuration cognitive + Ancrage"
    voiceover: |
      Placez votre pouce et votre index ensemble, doucement.
      C'est votre ancre de calme. Respirez dans cette connexion.
      Vous pouvez la retrouver à tout moment.
      
  - title: "Retour doux"
    start_s: 600
    end_s: 720
    technique: "Scan corporel + Gratitude"
    voiceover: |
      Prenez conscience de votre corps, de vos pieds au sommet de votre crâne.
      Remerciez-vous d'avoir pris ce temps.
      Quand vous êtes prêt, ouvrez doucement les yeux.

lyrics:
  refrain: "J'inspire calme, j'expire tension. Je reviens au centre."
  verses:
    - "Ici et maintenant, je pose mes pas"
    - "La vague monte et descend, je reste"
    - "Un souffle après l'autre, je m'ancre"

tcm:
  points: ["P6-Neiguan", "Yintang"]
  contraindications: []
  aromatherapy: "lavande"

immersion:
  tapping: true
  light_color: "chaud-ambré"
  breathwork_pattern: "4/6"

prompt_suno: "Calming 6/8, 68 BPM, dorian, felt piano + handpan, warm pads, whispered FR affirmations, no cymbal crashes, therapeutic ambient"
