preset_key: "apathie-demotivation"
title: "Apathie/Démotivation → Élan"
emotion_category: "apathie"
duration_target: 18

music:
  bpm: 100
  mode: "ionien"
  progression: "I–V–vi–IV"
  meter: "4/4"
  instruments: "piano pop + claps feutrés + arp doux + basse ronde"
  model: "V4_5"
  style_weight: 0.7
  weirdness: 0.3

segments:
  - title: "Éveil corporel"
    start_s: 0
    end_s: 120
    technique: "Activation physique douce"
    voiceover: |
      Bougez vos orteils. Puis vos doigts.
      Roulez doucement vos épaules.
      Votre corps existe. Il peut bouger.
      Un tout petit mouvement suffit pour commencer.

  - title: "Intentions Si/Alors"
    start_s: 120
    end_s: 300
    technique: "Planification d'implémentation"
    voiceover: |
      Pensez à UNE chose que vous aimeriez faire aujourd'hui.
      Si [situation], alors je [micro-action].
      Par exemple : Si je me lève, alors je bois un verre d'eau.
      Petit, précis, faisable.

  - title: "Imagerie de réussite"
    start_s: 300
    end_s: 600
    technique: "Visualisation guidée"
    voiceover: |
      Imaginez-vous accomplissant cette micro-action.
      Voyez-vous bouger. Sentez la satisfaction qui suit.
      Votre corps sait comment faire. Votre énergie revient par petites touches.

  - title: "Éveil progressif"
    start_s: 600
    end_s: 900
    technique: "Hypnose - Compte 1→5"
    voiceover: |
      Je compte de 1 à 5. À chaque nombre, vous vous sentez plus éveillé, plus présent.
      1... l'énergie revient dans vos jambes.
      2... dans votre poitrine.
      3... vos épaules se redressent.
      4... vos yeux s'ouvrent.
      5... vous êtes là, ancré, prêt.

  - title: "Premier pas"
    start_s: 900
    end_s: 1080
    technique: "Activation comportementale"
    voiceover: |
      Maintenant, si vous le pouvez, levez-vous.
      Faites un pas. Puis un autre.
      L'élan naît du mouvement. Vous l'avez déjà en vous.

lyrics:
  refrain: "Un pas puis un autre, je reviens dans mes pieds."
  verses:
    - "L'immobilité se fissure, je bouge"
    - "Un geste minuscule, c'est déjà beaucoup"
    - "L'énergie revient quand je lui fais de la place"

tcm:
  points: ["ST36-Zusanli", "LI11-Quchi"]
  contraindications: []
  aromatherapy: "citron/menthe"

immersion:
  tapping: false
  light_color: "blanc-froid-énergisant"
  breathwork_pattern: "3/3"
  props: "eau fraîche, lumière naturelle"

prompt_suno: "Light indie-house 100 BPM, clean claps, soft arps, FR small-steps motivational chorus, no loud hats, uplifting gentle energy"
