title: "Peur anticipatoire/Phobie → Tolérance"
emotion: "peur"
duration_min: 20
duration_max: 22

music:
  bpm: 62
  mode: "aeolian → dorian"
  progression: "vi–IV–I"
  time_signature: "6/8"
  style: "handpan drones"
  instruments: ["handpan", "drones doux"]
  prompt: "Handpan 6/8 62 BPM, aeolian→dorian, FR guided exposure, no stingers."

segments:
  - title: "Safe place"
    start: 0
    end: 180
    type: "safety"
    voiceover: |
      Imagine un lieu où tu es en sécurité.
      Les détails, les couleurs, les sons.
      Tu peux toujours y revenir.
    
  - title: "Hiérarchie d'exposition"
    start: 180
    end: 360
    type: "hierarchy"
    voiceover: |
      La situation qui te fait peur, de 1 à 10.
      On commence par le 3. Juste imaginer.
      Tu y vas à ton rythme.
    
  - title: "Exposition imaginale - Scène 1"
    start: 360
    end: 660
    type: "exposure"
    voiceover: |
      Imagine la scène légère. Respire.
      Reste avec cette image. L'anxiété monte puis redescend.
      Tu peux rester. Tu tolères.
    
  - title: "Retour au safe place"
    start: 660
    end: 780
    type: "return"
    voiceover: |
      Reviens dans ton lieu sûr.
      Respire profondément. Tu as fait un pas.
    
  - title: "Exposition imaginale - Scène 2"
    start: 780
    end: 1020
    type: "exposure"
    voiceover: |
      Cette fois un peu plus intense.
      Même processus : anxiété monte, puis descend.
      Tu restes. Tu apprends que tu peux.
    
  - title: "Consolidation et futurisation"
    start: 1020
    end: 1320
    type: "consolidation"
    voiceover: |
      Imagine-toi dans 1 mois, ayant fait ces pas.
      Plus fort, plus confiant. Tapping gauche-droite.
      J'avance par petits pas, je peux rester.

tcm:
  points: ["P6", "KD1"]
  warnings: []
  aromatherapy: "Lavande"

immersion:
  light: "progressive (sombre → douce)"
  sounds: ["tapping L/R"]
  props: ["carte mentale des scènes"]

affirmations:
  - "J'avance par petits pas, je peux rester."
  - "L'anxiété monte puis redescend, je tolère."
