title: "Jalousie/Envie → Recentrage"
emotion: "jalousie"
duration_min: 18
duration_max: 20

music:
  bpm: 76
  mode: "mixolydian"
  progression: "I–IV–V"
  style: "afro-lofi"
  instruments: ["guitare high-life douce"]
  prompt: "Afro-lofi 76 BPM, mixolydian, soft high-life guitar, FR values/gratitude cues, no sharp transients."

segments:
  - title: "Reconnaissance de l'émotion"
    start: 0
    end: 120
    type: "awareness"
    voiceover: |
      La jalousie est là. Elle te dit quelque chose.
      Peut-être un besoin non écouté.
      Tu la regardes sans jugement.
    
  - title: "Restructuration cognitive"
    start: 120
    end: 360
    type: "reframing"
    voiceover: |
      "Il a ce que je veux" devient "Qu'est-ce que je veux vraiment ?"
      "Je ne suis pas assez" devient "Quelle est ma voie à moi ?"
      Tu reviens à ton chemin.
    
  - title: "Clarification des valeurs"
    start: 360
    end: 600
    type: "values"
    voiceover: |
      Qu'est-ce qui compte pour toi ? Vraiment ?
      Famille, créativité, liberté, connexion ?
      Tu choisis tes pas selon tes valeurs, pas celles des autres.
    
  - title: "Gratitude ciblée"
    start: 600
    end: 840
    type: "gratitude"
    voiceover: |
      Trois choses dans ta vie qui fonctionnent.
      Trois choses que tu as construites.
      Tu es sur ton propre chemin.
    
  - title: "Consolidation et ancrage"
    start: 840
    end: 1080
    type: "consolidation"
    voiceover: |
      Main sur ton poignet. Respiration rythmée.
      Je reviens à ma voie, à mes pas.
      Percussions légères. Lumière dorée. Tu es ancré.

tcm:
  points: ["LV3"]
  warnings: []
  aromatherapy: "Orange douce"

immersion:
  light: "dorée"
  sounds: ["percussions mains légères"]
  props: []

affirmations:
  - "Je reviens à ma voie, à mes pas."
  - "Ma route est unique, je la célèbre."
