title: "Solitude/Isolement → Connexion"
emotion: "solitude"
duration_min: 20
duration_max: 22

music:
  bpm: 78
  mode: "ionian"
  progression: "I–vi–IV–V"
  style: "choirs airy"
  instruments: ["chœurs aérés", "clochettes douces"]
  prompt: "Airy choirs 78 BPM, gentle bells, FR connection imagery, no reverb tails too long."

segments:
  - title: "Validation de l'émotion"
    start: 0
    end: 120
    type: "validation"
    voiceover: |
      Se sentir seul, c'est humain.
      Tu n'es pas faible. Tu as besoin de lien.
      C'est normal.
    
  - title: "Lettre à un ami"
    start: 120
    end: 420
    type: "cognitive"
    voiceover: |
      Imagine écrire à un ami que tu aimes.
      Pas pour envoyer. Juste pour sentir le lien.
      Les mots créent un pont.
    
  - title: "Mémoire de chaleur"
    start: 420
    end: 660
    type: "imagery"
    voiceover: |
      Souviens-toi d'un moment où tu t'es senti connecté.
      Un regard, un rire, une présence.
      Ce lien existe encore en toi.
    
  - title: "Plan micro-contact"
    start: 660
    end: 900
    type: "behavioral"
    voiceover: |
      Un message à envoyer. Une personne à appeler.
      Pas besoin de grand geste. Un petit pas suffit.
      Tu tends la main.
    
  - title: "Main sur cœur et tapping"
    start: 900
    end: 1140
    type: "anchoring"
    voiceover: |
      Main sur ton cœur. Tapping lent.
      "Je tends la main, la chaleur répond."
      Tu n'es pas seul dans cet univers.
    
  - title: "Consolidation"
    start: 1140
    end: 1320
    type: "consolidation"
    voiceover: |
      Chœurs autour de toi. Clochettes.
      Je tends la main; la chaleur répond.
      La connexion commence par un pas.

tcm:
  points: ["CV17"]
  warnings: []
  aromatherapy: "Rose, néroli"

immersion:
  light: "chaude"
  sounds: ["chœurs légers"]
  props: ["main sur cœur"]

affirmations:
  - "Je tends la main; la chaleur répond."
  - "La connexion commence par un petit pas."
