title: "Douleur physique légère → Apaisement"
emotion: "douleur"
duration_min: 20
duration_max: 22

music:
  bpm: "60–64"
  mode: "dorian"
  style: "drone warm"
  instruments: ["drones chauds", "flûte basse"]
  prompt: "Warm drone 62 BPM + low flute, FR acceptance imagery, no sharp attacks."

segments:
  - title: "Validation de la douleur"
    start: 0
    end: 120
    type: "validation"
    voiceover: |
      La douleur est là. Tu ne l'as pas inventée.
      Elle fait partie de ton expérience.
      Tu peux la reconnaître sans catastrophiser.
    
  - title: "Recadrage catastrophisme"
    start: 120
    end: 360
    type: "cognitive"
    voiceover: |
      "C'est insupportable" devient "C'est difficile, et je peux respirer."
      "Ça ne partira jamais" devient "Ça fluctue."
      Tu élargis l'espace autour de la douleur.
    
  - title: "Pacing - Le rythme juste"
    start: 360
    end: 600
    type: "behavioral"
    voiceover: |
      Activité puis repos. Activité puis repos.
      Tu ne forces pas. Tu écoutes ton corps.
      Le rythme devient ton allié.
    
  - title: "Déplacement perceptif"
    start: 600
    end: 900
    type: "hypnosis"
    voiceover: |
      Porte ton attention sur une autre sensation.
      La chaleur d'une bouillotte. La douceur d'un tissu.
      Tu déplaces le focus. La douleur reste, mais tu élargis.
    
  - title: "Métaphore rivière"
    start: 900
    end: 1140
    type: "imagery"
    voiceover: |
      La douleur est une rivière. Tu es sur la berge.
      Elle coule, tu la regardes. Tu n'es pas la rivière.
      Tu respires, tu élargis autour d'elle.
    
  - title: "Consolidation"
    start: 1140
    end: 1320
    type: "consolidation"
    voiceover: |
      Bouillotte. Lumière chaude. Flûte basse.
      Je respire, j'élargis autour de la douleur.
      Je suis plus grand que cette sensation.

tcm:
  points: ["LI4", "ST36"]
  warnings: ["LI4 contre-indiqué grossesse"]
  aromatherapy: "Menthe, lavande"

immersion:
  light: "chaude"
  sounds: ["drone"]
  props: ["bouillotte"]

affirmations:
  - "Je respire, j'élargis autour de la douleur."
  - "Je suis plus grand que cette sensation."
