title: "Manque de confiance/Auto-sabotage → Assurance douce"
emotion: "confiance"
duration_min: 20
duration_max: 22

music:
  bpm: "86–92"
  mode: "ionian"
  style: "gentle pop"
  instruments: ["arp doux", "basse ronde", "groove léger"]
  prompt: "Gentle pop 90 BPM, soft arps, FR self-efficacy lines."

segments:
  - title: "Identification croyances de noyau"
    start: 0
    end: 180
    type: "cognitive"
    voiceover: |
      "Je ne suis pas capable." D'où vient cette voix ?
      C'est une croyance apprise, pas un fait.
      Tu peux la questionner.
    
  - title: "Preuves contraires"
    start: 180
    end: 420
    type: "cognitive"
    voiceover: |
      Rappelle-toi une fois où tu as réussi.
      Même petit. Tu as appris, tu as fait.
      Les preuves sont là. Tu es capable.
    
  - title: "Plan micro-audace"
    start: 420
    end: 660
    type: "behavioral"
    voiceover: |
      Une chose que tu peux faire demain.
      Petite, concrète, faisable.
      Un pas après l'autre.
    
  - title: "Futurisation de réussite"
    start: 660
    end: 960
    type: "hypnosis"
    voiceover: |
      Imagine-toi dans 1 mois, ayant fait ce pas.
      Comment tu te sens ? Quelle fierté ?
      Ce futur est possible. Tu le construis.
    
  - title: "Posture et ancrage"
    start: 960
    end: 1140
    type: "body"
    voiceover: |
      Redresse ton dos. Souris légèrement.
      Ta posture influence ton mental.
      Tu te tiens droit, ancré.
    
  - title: "Consolidation"
    start: 1140
    end: 1320
    type: "consolidation"
    voiceover: |
      Je prends ma place, pas à pas.
      Je suis capable. Les preuves sont là.
      Arp doux. Groove léger. Tu avances.

tcm:
  points: ["CV6", "ST36"]
  warnings: []
  aromatherapy: "Citron, romarin"

immersion:
  light: "lumière progressive"
  sounds: []
  props: ["posture ancrée"]

affirmations:
  - "Je prends ma place, pas à pas."
  - "Je suis capable. Les preuves sont là."
