title: "Perfectionnisme/Contrôle → Souplesse"
emotion: "perfectionnisme"
duration_min: 18
duration_max: 20

music:
  bpm: "72–78"
  mode: "mixolydian"
  style: "neo-soul laid-back"
  instruments: ["Rhodes", "guitare nylon"]
  prompt: "Neo-soul 76 BPM, FR flexibility cues, no harsh percs."

segments:
  - title: "Reconnaissance du perfectionnisme"
    start: 0
    end: 120
    type: "awareness"
    voiceover: |
      Le perfectionnisme te protège de l'échec.
      Mais il t'empêche d'avancer.
      Tu peux lâcher un peu. Assez bien, c'est suffisant.
    
  - title: "Expérience volontairement imparfaite"
    start: 120
    end: 360
    type: "behavioral"
    voiceover: |
      Fais quelque chose d'imparfait, exprès.
      Un email court. Un dessin simple.
      Observe : le monde ne s'effondre pas.
    
  - title: "ACT - Laisser de l'espace"
    start: 360
    end: 600
    type: "acceptance"
    voiceover: |
      Tu peux avoir l'envie de contrôler, et avancer quand même.
      L'anxiété est là, tu fais ton choix quand même.
      Tu laisses de l'espace à l'imprévu.
    
  - title: "Métaphore du bambou"
    start: 600
    end: 840
    type: "imagery"
    voiceover: |
      Le bambou plie, il ne casse pas.
      La souplesse est une force.
      Tu acceptes les ajustements en cours de route.
    
  - title: "Relâchement épaules et tapping"
    start: 840
    end: 1020
    type: "body"
    voiceover: |
      Relâche tes épaules. Tapping bilatéral lent.
      Suffisamment bien, c'est parfait pour avancer.
      Tu te donnes la permission d'être humain.
    
  - title: "Consolidation"
    start: 1020
    end: 1080
    type: "consolidation"
    voiceover: |
      Rhodes doux. Guitare nylon.
      Suffisamment bien, c'est parfait pour avancer.
      Tu lâches prise, tu gagnes en légèreté.

tcm:
  points: ["LV3", "PC6"]
  warnings: []
  aromatherapy: "Lavande"

immersion:
  light: "douce"
  sounds: ["tapping bilatéral lent"]
  props: []

affirmations:
  - "Suffisamment bien, c'est parfait pour avancer."
  - "Je plie, je ne casse pas."
