title: "Nostalgie/Mélancolie → Douceur présente"
emotion: "nostalgie"
duration_min: 20
duration_max: 22

music:
  bpm: "68–72"
  mode: "ionian"
  progression: "vi–IV–I–V"
  style: "retro dream-pop"
  instruments: ["chorus/tape feel"]
  prompt: "Retro dream-pop 70 BPM, tape feel, FR gentle nostalgia lines."

segments:
  - title: "Accueil de la mélancolie"
    start: 0
    end: 180
    type: "validation"
    voiceover: |
      La nostalgie est douce-amère.
      Elle te rappelle des moments précieux.
      Tu peux l'accueillir sans t'y perdre.
    
  - title: "Gratitude pour les souvenirs"
    start: 180
    end: 420
    type: "gratitude"
    voiceover: |
      Ces moments ont existé. Tu les as vécus.
      Ils t'ont façonné. Merci pour ces souvenirs.
      Ils restent en toi.
    
  - title: "Pont au présent"
    start: 420
    end: 720
    type: "hypnosis"
    voiceover: |
      Le passé te tend la main.
      Prends la douceur, la chaleur.
      Et reviens dans l'instant présent, enrichi.
    
  - title: "Souvenirs ressources"
    start: 720
    end: 960
    type: "imagery"
    voiceover: |
      Ces moments te donnent de la force.
      Tu peux y puiser quand tu en as besoin.
      Albums photos mentaux. Lumière dorée.
    
  - title: "Ancrage présent"
    start: 960
    end: 1200
    type: "grounding"
    voiceover: |
      Sens tes pieds au sol. Tes mains sur ton corps.
      Maintenant, ici. La vie continue.
      Tu gardes le tendre, tu habites l'instant.
    
  - title: "Consolidation"
    start: 1200
    end: 1320
    type: "consolidation"
    voiceover: |
      Chorus doux. Tape feel.
      Je garde le tendre, j'habite l'instant.
      Le passé m'enrichit, je vis maintenant.

tcm:
  points: ["HT7", "Yintang"]
  warnings: []
  aromatherapy: "Vanille, bois de santal"

immersion:
  light: "dorée"
  sounds: []
  props: ["albums photos mentaux"]

affirmations:
  - "Je garde le tendre, j'habite l'instant."
  - "Le passé m'enrichit, je vis maintenant."
