title: "Concentration/Flow → Focus stable"
emotion: "concentration"
duration_min: 18
duration_max: 20

music:
  bpm: "85–95"
  mode: "lofi instrumental"
  style: "lofi focus"
  instruments: ["patterns répétitifs doux", "pas de voix"]
  prompt: "Lofi focus 90 BPM, instrumental only, no vocals, no risers."

segments:
  - title: "Pomodoro 10/2"
    start: 0
    end: 120
    type: "technique"
    voiceover: |
      10 minutes de focus. Une seule chose.
      Puis 2 minutes de pause.
      Répéter. Le cerveau aime le rythme.
    
  - title: "ACT - Revenir"
    start: 120
    end: 360
    type: "attention"
    voiceover: |
      Quand ton esprit s'échappe, remarque.
      Pas de jugement. Juste : "Ah, je suis parti."
      Reviens. Encore et encore.
    
  - title: "Tunnel attentionnel"
    start: 360
    end: 720
    type: "hypnosis"
    voiceover: |
      Imagine ton attention comme un tunnel.
      Les distractions rebondissent à l'extérieur.
      Tu es dans le tunnel, concentré.
    
  - title: "Ancrage corps"
    start: 720
    end: 960
    type: "grounding"
    voiceover: |
      Sens tes pieds. Tes mains sur le clavier ou le papier.
      Reviens dans ton corps. Ici, maintenant.
      Une chose à la fois.
    
  - title: "Timer et consolidation"
    start: 960
    end: 1080
    type: "consolidation"
    voiceover: |
      Lofi patterns. Casque. Timer discret.
      Ici, maintenant, une chose à la fois.
      Tu es dans le flow.

tcm:
  points: ["Yintang", "KD1"]
  warnings: []
  aromatherapy: "Menthe poivrée, romarin"

immersion:
  light: "neutre, stable"
  sounds: ["lofi instrumental"]
  props: ["casque", "timer discret"]

affirmations:
  - "Ici, maintenant, une chose à la fois."
  - "Mon attention est un muscle, je l'entraîne."
