rules:
  - when: { valence: "high", arousal: "low" }
    set:
      style: "lofi neo-soul, touches afro chill, Rhodes + guitare palm-mute, field recordings mer lointaine"
      model: "V4_5"
      instrumental: true
      negativeTags: "aggressive drums, harsh, screech"
      styleWeight: 0.7
      weirdnessConstraint: 0.3
      durationSeconds: 150
  - when: { valence: "low", arousal: "low" }
    set:
      style: "ambient minimal, pads chaleureux, reverb ample"
      model: "V4"
      instrumental: true
      durationSeconds: 120
  - when: { arousal: "high" }
    set:
      style: "organic house soft, percussions feutrées, groove régulier"
      model: "V4_5"
      instrumental: false
      negativeTags: "distortion harsh, clipping"
      durationSeconds: 150
  - when: { label: "nostalgia" }
    set:
      style: "retro dream-pop, chorus/tape feel, suites vi–IV–I–V"
      model: "V4_5"
      instrumental: false
      durationSeconds: 150
fallback:
  style: "lofi chill upbeat"
  model: "V4_5"
  instrumental: true
