/**
 * RouterV2 Registry - Toutes les routes canoniques
 * TICKET: FE/BE-Router-Cleanup-01
 */

import { RouteMeta } from './schema';

export const ROUTES_REGISTRY: RouteMeta[] = [
  // ═══════════════════════════════════════════════════════════
  // ROUTES PUBLIQUES
  // ═══════════════════════════════════════════════════════════
  {
    name: 'home',
    path: '/',
    segment: 'public',
    layout: 'marketing',
    component: 'HomePage',
  },
  {
    name: 'about',
    path: '/about',
    segment: 'public',
    layout: 'marketing',
    component: 'AboutPage',
  },
  {
    name: 'contact',
    path: '/contact',
    segment: 'public',
    layout: 'marketing',
    component: 'ContactPage',
  },
  {
    name: 'help',
    path: '/help',
    segment: 'public',
    layout: 'marketing',
    component: 'HelpPage',
  },
  {
    name: 'demo',
    path: '/demo',
    segment: 'public',
    layout: 'marketing',
    component: 'DemoPage',
  },
  {
    name: 'onboarding',
    path: '/onboarding',
    segment: 'public',
    layout: 'marketing',
    component: 'OnboardingPage',
  },
  {
    name: 'privacy',
    path: '/privacy',
    segment: 'public',
    layout: 'marketing',
    component: 'PrivacyPage',
  },
  {
    name: 'b2c-landing',
    path: '/b2c',
    segment: 'public',
    layout: 'marketing',
    component: 'HomeB2C',
    aliases: ['/choose-mode'],
  },
  {
    name: 'b2b-landing',
    path: '/entreprise',
    segment: 'public', 
    layout: 'marketing',
    component: 'HomeB2B',
    aliases: ['/b2b'],
  },
  {
    name: 'b2b-landing-detailed',
    path: '/b2b/landing',
    segment: 'public',
    layout: 'marketing',
    component: 'B2BLandingPage',
  },
  {
    name: 'b2b-selection',
    path: '/b2b/selection',
    segment: 'b2b',
    layout: 'app',
    guard: true,
    component: 'B2BSelectionPage',
  },
  {
    name: 'login',
    path: '/login',
    segment: 'public',
    layout: 'marketing',
    component: 'LoginPage',
    aliases: ['/auth', '/b2c/login', '/b2b/user/login', '/b2b/admin/login'],
  },
  {
    name: 'signup',
    path: '/signup',
    segment: 'public',
    layout: 'marketing', 
    component: 'SignupPage',
    aliases: ['/register', '/b2c/register', '/b2b/user/register'],
  },

  // ═══════════════════════════════════════════════════════════
  // APP DISPATCHER & DASHBOARDS
  // ═══════════════════════════════════════════════════════════
  {
    name: 'app-gate',
    path: '/app',
    segment: 'consumer',
    layout: 'app',
    component: 'AppGatePage',
    guard: true,
  },
  {
    name: 'consumer-home',
    path: '/app/home',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CDashboardPage',
    guard: true,
    aliases: ['/b2c/dashboard', '/dashboard'],
  },
  {
    name: 'employee-home',
    path: '/app/collab',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BUserDashboardPage',
    guard: true,
    aliases: ['/b2b/user/dashboard'],
  },
  {
    name: 'manager-home',
    path: '/app/rh',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BAdminDashboardPage',
    guard: true,
    aliases: ['/b2b/admin/dashboard'],
  },

  {
    name: 'navigation',
    path: '/navigation',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'CompleteNavigationMenu',
    guard: true,
    aliases: ['/modules', '/all-modules'],
  },

  // ═══════════════════════════════════════════════════════════
  // MODULES FONCTIONNELS (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'scan',
    path: '/app/scan',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CScanPage',
    guard: true,
    aliases: ['/scan'],
  },
  {
    name: 'music',
    path: '/app/music',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CMusicEnhanced',
    guard: true,
    aliases: ['/music'],
  },
  {
    name: 'coach',
    path: '/app/coach',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CAICoachPage',
    guard: true,
    aliases: ['/coach'],
  },
  {
    name: 'journal',
    path: '/app/journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CJournalPage',
    guard: true,
    aliases: ['/journal'],
  },
  {
    name: 'vr',
    path: '/app/vr',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CVRPage',
    guard: true,
    aliases: ['/vr'],
  },
  
  // ═══════════════════════════════════════════════════════════
  // MODULES FUN-FIRST (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'flash-glow',
    path: '/app/flash-glow',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CFlashGlowPage',
    guard: true,
    aliases: ['/flash-glow', '/instant-glow'],
  },
  {
    name: 'breath',
    path: '/app/breath',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CBreathworkPage',
    guard: true,
    aliases: ['/breathwork'],
  },
  {
    name: 'face-ar',
    path: '/app/face-ar',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CARFiltersPage',
    guard: true,
    aliases: ['/ar-filters'],
  },
  {
    name: 'emotion-scan',
    path: '/app/emotion-scan',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CEmotionScanPage',
    guard: true,
    aliases: ['/emotion-scan'],
  },
  {
    name: 'voice-journal',
    path: '/app/voice-journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CVoiceJournalPage',
    guard: true,
    aliases: ['/voice-journal'],
  },
  {
    name: 'emotions',
    path: '/app/emotions',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CEmotionsPage',
    guard: true,
    aliases: ['/emotions'],
  },
  {
    name: 'community',
    path: '/app/community',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CCommunityPage',
    guard: true,
    aliases: ['/community'],
  },
  {
    name: 'bubble-beat',
    path: '/app/bubble-beat',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CBubbleBeatPage',
    guard: true,
    aliases: ['/bubble-beat'],
  },
  {
    name: 'screen-silk',
    path: '/app/screen-silk',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CScreenSilkBreakPage',
    guard: true,
    aliases: ['/screen-silk-break'],
  },
  {
    name: 'vr-galaxy',
    path: '/app/vr-galaxy',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CVRGalactiquePage',
    guard: true,
    aliases: ['/vr-galactique'],
  },
  {
    name: 'boss-grit',
    path: '/app/boss-grit',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CBossLevelGritPage',
    guard: true,
    aliases: ['/boss-level-grit'],
  },
  {
    name: 'mood-mixer',
    path: '/app/mood-mixer',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CMoodMixerPage',
    guard: true,
    aliases: ['/mood-mixer'],
  },
  {
    name: 'ambition-arcade',
    path: '/app/ambition-arcade',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CAmbitionArcadePage',
    guard: true,
    aliases: ['/ambition-arcade'],
  },
  {
    name: 'bounce-back',
    path: '/app/bounce-back',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CBounceBackBattlePage',
    guard: true,
    aliases: ['/bounce-back-battle'],
  },
  {
    name: 'story-synth',
    path: '/app/story-synth',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CStorySynthLabPage',
    guard: true,
    aliases: ['/story-synth-lab'],
  },
  {
    name: 'social-cocon-b2c',
    path: '/app/social-cocon',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CSocialCoconPage',
    guard: true,
    aliases: ['/social-cocon'],
  },

  // ═══════════════════════════════════════════════════════════
  // ANALYTICS & DATA (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'leaderboard',
    path: '/app/leaderboard',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CGamificationPage',
    guard: true,
    aliases: ['/gamification'],
  },
  {
    name: 'activity',
    path: '/app/activity',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CWeeklyBarsPage',
    guard: true,
    aliases: ['/weekly-bars', '/activity-history'],
  },
  {
    name: 'heatmap',
    path: '/app/heatmap',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CHeatmapVibesPage',
    guard: true,
    aliases: ['/heatmap-vibes'],
  },

  // ═══════════════════════════════════════════════════════════
  // PARAMÈTRES & COMPTE
  // ═══════════════════════════════════════════════════════════
  {
    name: 'settings-general',
    path: '/settings/general',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CSettingsPage',
    guard: true,
    aliases: ['/settings', '/preferences'],
  },
  {
    name: 'settings-profile',
    path: '/settings/profile',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CProfileSettingsPage',
    guard: true,
    aliases: ['/profile-settings'],
  },
  {
    name: 'settings-privacy',
    path: '/settings/privacy',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CPrivacyTogglesPage',
    guard: true,
    aliases: ['/privacy-toggles'],
  },
  {
    name: 'settings-notifications',
    path: '/settings/notifications',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CNotificationsPage',
    guard: true,
    aliases: ['/notifications'],
  },
  {
    name: 'settings-data-privacy',
    path: '/settings/data-privacy',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CDataPrivacyPage',
    guard: true,
    aliases: ['/data-privacy'],
  },

  // ═══════════════════════════════════════════════════════════
  // B2B FEATURES (EMPLOYEE)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'teams',
    path: '/app/teams',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BTeamsPage',
    guard: true,
    aliases: ['/teams'],
  },
  {
    name: 'social-cocon-b2b',
    path: '/app/social',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BSocialCoconPage',
    guard: true,
  },

  // ═══════════════════════════════════════════════════════════
  // B2B ADMIN (MANAGER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'admin-reports',
    path: '/app/reports',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BReportsPage',
    guard: true,
    aliases: ['/reports'],
  },
  {
    name: 'admin-events',
    path: '/app/events',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BEventsPage',
    guard: true,
    aliases: ['/events'],
  },
  {
    name: 'admin-optimization',
    path: '/app/optimization',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BOptimisationPage',
    guard: true,
    aliases: ['/optimisation'],
  },
  {
    name: 'admin-security',
    path: '/app/security',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BSecurityPage',
    guard: true,
    aliases: ['/security'],
  },
  {
    name: 'admin-audit',
    path: '/app/audit',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BAuditPage',
    guard: true,
    aliases: ['/audit'],
  },
  {
    name: 'admin-accessibility',
    path: '/app/accessibility',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BAccessibilityPage',
    guard: true,
    aliases: ['/accessibility'],
  },

  // ═══════════════════════════════════════════════════════════
  // SYSTÈME & MONITORING
  // ═══════════════════════════════════════════════════════════
  {
    name: 'api-monitoring',
    path: '/system/api-monitoring',
    segment: 'system',
    layout: 'app',
    guard: true,
    role: 'admin',
    component: 'ApiMonitoringPage',
  },

  // ═══════════════════════════════════════════════════════════
  // PAGES SYSTÈME
  // ═══════════════════════════════════════════════════════════
  {
    name: 'unauthorized',
    path: '/401',
    segment: 'public',
    layout: 'marketing',
    component: 'UnauthorizedPage',
  },
  {
    name: 'forbidden',
    path: '/403',
    segment: 'public',
    layout: 'marketing',
    component: 'ForbiddenPage',
  },
  {
    name: 'not-found',
    path: '/404',
    segment: 'public',
    layout: 'marketing',
    component: 'NotFoundPage',
  },
  {
    name: 'server-error',
    path: '/503',
    segment: 'public',
    layout: 'marketing',
    component: 'ServerErrorPage',
  },
];