// @ts-nocheck
/**
 * RouterV2 Registry - Toutes les routes canoniques
 * TICKET: FE/BE-Router-Cleanup-01
 */

import { RouteMeta } from './schema';

export const ROUTES_REGISTRY: RouteMeta[] = [
  // ═══════════════════════════════════════════════════════════
  // ROUTES PUBLIQUES
  // ═══════════════════════════════════════════════════════════
  {
    name: 'home',
    path: '/',
    segment: 'public',
    layout: 'marketing',
    component: 'HomePage',
    guard: false, // Pas de guard - accessible à tous
  },
  {
    name: 'pricing',
    path: '/pricing',
    segment: 'public',
    layout: 'marketing',
    component: 'PricingPageWorking',
    guard: false,
    aliases: ['/tarifs'],
  },
  // /home redirect supprimé - confus et inutile
  {
    name: 'about',
    path: '/about',
    segment: 'public',
    layout: 'marketing',
    component: 'AboutPage',
  },
  {
    name: 'contact',
    path: '/contact',
    segment: 'public',
    layout: 'marketing',
    component: 'ContactPage',
  },
  {
    name: 'help',
    path: '/help',
    segment: 'public',
    layout: 'marketing',
    component: 'HelpPage',
  },
  {
    name: 'store',
    path: '/store',
    segment: 'public',
    layout: 'marketing',
    component: 'StorePage',
    guard: false,
  },
  {
    name: 'product-detail',
    path: '/store/product/:handle',
    segment: 'public',
    layout: 'marketing',
    component: 'ProductDetailPage',
    guard: false,
  },
  {
    name: 'demo',
    path: '/demo',
    segment: 'public',
    layout: 'marketing',
    component: 'DemoPage',
  },
  {
    name: 'onboarding',
    path: '/onboarding',
    segment: 'public',
    layout: 'marketing',
    component: 'OnboardingPage',
  },
  {
    name: 'privacy',
    path: '/privacy',
    segment: 'public',
    layout: 'marketing',
    component: 'PrivacyPage',
    aliases: ['/politique-confidentialite'],
  },
  {
    name: 'legal-mentions',
    path: '/legal/mentions',
    segment: 'public',
    layout: 'marketing',
    component: 'MentionsLegalesPage',
    guard: false,
  },
  {
    name: 'legal-privacy',
    path: '/legal/privacy',
    segment: 'public',
    layout: 'marketing',
    component: 'PrivacyPolicyPage',
    guard: false,
  },
  {
    name: 'legal-terms',
    path: '/legal/terms',
    segment: 'public',
    layout: 'marketing',
    component: 'TermsPage',
    guard: false,
  },
  {
    name: 'legal-sales',
    path: '/legal/sales',
    segment: 'public',
    layout: 'marketing',
    component: 'SalesTermsPage',
    guard: false,
  },
  {
    name: 'legal-cookies',
    path: '/legal/cookies',
    segment: 'public',
    layout: 'marketing',
    component: 'CookiesPage',
    guard: false,
  },
  {
    name: 'legal-licenses',
    path: '/legal/licenses',
    segment: 'public',
    layout: 'marketing',
    component: 'LicensesPage',
    guard: false,
  },
  {
    name: 'b2c-landing',
    path: '/b2c',
    segment: 'public',
    layout: 'marketing',
    component: 'HomeB2CPage',
  },
  {
    name: 'b2b-landing',
    path: '/entreprise',
    segment: 'public', 
    layout: 'marketing',
    component: 'B2BEntreprisePage',
    aliases: ['/b2b'],
  },
  // /b2b/landing -> redirection vers /entreprise
  {
    name: 'b2b-landing-redirect',
    path: '/b2b/landing',
    segment: 'public',
    layout: 'marketing',
    component: 'RedirectToEntreprise',
    deprecated: true,
  },
  {
    name: 'b2b-selection',
    path: '/b2b/selection',
    segment: 'b2b',
    layout: 'app',
    guard: true,
    component: 'B2BSelectionPage',
  },
  {
    name: 'b2b-reports-heatmap',
    path: '/b2b/reports',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    guard: true,
    component: 'B2BReportsHeatmapPage',
  },
  {
    name: 'login',
    path: '/login',
    segment: 'public',
    layout: 'marketing',
    component: 'UnifiedLoginPage',
    aliases: ['/auth', '/b2c/login', '/b2b/user/login', '/b2b/admin/login'],
  },
  {
    name: 'signup',
    path: '/signup',
    segment: 'public',
    layout: 'marketing', 
    component: 'SignupPage',
    aliases: ['/register', '/b2c/register', '/b2b/user/register'],
  },

  // ═══════════════════════════════════════════════════════════
  // APP DISPATCHER & DASHBOARDS
  // ═══════════════════════════════════════════════════════════
  {
    name: 'app-gate',
    path: '/app',
    segment: 'consumer',
    layout: 'app',
    component: 'AppGatePage',
    guard: false,
  },
  {
    name: 'consumer-home',
    path: '/app/consumer/home',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CDashboardPage',
    guard: true,
    aliases: ['/app/home', '/b2c/dashboard', '/dashboard'],
  },
  {
    name: 'employee-home',
    path: '/app/collab',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BCollabDashboard',
    guard: true,
    aliases: ['/b2b/user/dashboard'],
  },
  {
    name: 'manager-home',
    path: '/app/rh',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BRHDashboard',
    guard: true,
    aliases: ['/b2b/admin/dashboard'],
  },

  // ═══════════════════════════════════════════════════════════
  // MODULES FONCTIONNELS (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'modules-dashboard',
    path: '/app/modules',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ModulesDashboard',
    guard: true,
  },
  {
    name: 'scan',
    path: '/app/scan',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'B2CScanPage',
    guard: true,
    requireAuth: true,
    aliases: ['/scan'],
  },
  // scan-facial supprimé - fusionné dans scan principal (mode caméra)
  {
    name: 'scan-voice',
    path: '/app/scan/voice',
    segment: 'consumer',
    layout: 'simple',
    component: 'VoiceScanPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'scan-text',
    path: '/app/scan/text',
    segment: 'consumer',
    layout: 'simple',
    component: 'TextScanPage',
    guard: true,
  },
  {
    name: 'music',
    path: '/app/music',
    segment: 'public',
    layout: 'simple',
    component: 'B2CMusicEnhanced',
    guard: false,
    aliases: ['/music'],
  },
  {
    name: 'parcours-xl',
    path: '/app/parcours-xl',
    segment: 'public',
    layout: 'simple',
    component: 'ParcoursXL',
    guard: false,
    aliases: ['/parcours-xl'],
  },
  // emotion-music supprimé - utiliser /app/music
  // emotion-music-library supprimé - utiliser /app/music
  {
    name: 'music-premium',
    path: '/app/music-premium',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CMusicTherapyPremiumPage',
    guard: true,
    aliases: ['/music-therapy-premium'],
  },
  // Route supprimée - fonctionnalité intégrée dans B2CMusicEnhanced
  // music-library supprimé - fonctionnalité dans B2CMusicEnhanced
  {
    name: 'coach',
    path: '/app/coach',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CAICoachPage',
    guard: true,
    aliases: ['/coach'],
  },
  {
    name: 'coach-programs',
    path: '/app/coach/programs',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'CoachProgramsPage',
    guard: true,
  },
  {
    name: 'coach-sessions',
    path: '/app/coach/sessions',
    segment: 'consumer',
    role: 'consumer',
    layout: 'simple',
    component: 'CoachSessionsPage',
    guard: true,
  },
  {
    name: 'coach-micro',
    path: '/app/coach-micro',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CAICoachMicroPage',
    guard: true,
    aliases: ['/coach-micro-decisions'],
  },
  {
    name: 'journal',
    path: '/app/journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CJournalPage',
    guard: true,
    aliases: ['/journal', '/voice-journal'],
  },
  {
    name: 'journal-new',
    path: '/app/journal-new',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalNewPage',
    guard: true,
    requireAuth: true,
    aliases: ['/journal/new'],
  },
  {
    name: 'weekly-bars',
    path: '/app/weekly-bars',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CWeeklyBarsPage',
    guard: true,
    requireAuth: true,
    aliases: ['/weekly-bars', '/bars'],
  },
  {
    name: 'vr',
    path: '/app/vr',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CVRGalaxyPage',
    guard: true,
    aliases: ['/vr'],
  },
  
  // ═══════════════════════════════════════════════════════════
  // B2C INTEGRATION - PARTICULIER ROUTES
  // ═══════════════════════════════════════════════════════════
  {
    name: 'mode-selection',
    path: '/mode-selection',
    segment: 'public',
    layout: 'simple',
    component: 'ModeSelectionPage',
    guard: false,
    aliases: ['/choose-mode'],
  },
  {
    name: 'b2c-dashboard',
    path: '/app/particulier',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CDashboardPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'b2c-mood',
    path: '/app/particulier/mood',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CScanPage',
    guard: true,
    requireAuth: true,
  },
  // b2c-music supprimé - utiliser /app/music avec B2CMusicEnhanced

  // ═══════════════════════════════════════════════════════════
  // MODULES FUN-FIRST (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'flash-glow',
    path: '/app/flash-glow',
    segment: 'public',
    layout: 'simple',
    component: 'B2CFlashGlowPage',
    guard: false,
    aliases: ['/flash-glow', '/instant-glow', '/b2c-flash-glow', '/flash-glow-advanced'],
  },
  {
    name: 'breath',
    path: '/app/breath',
    segment: 'public',
    layout: 'simple',
    component: 'B2CBreathworkPage',
    guard: false,
    aliases: ['/breathwork', '/breathwork-adaptive'],
  },
  {
    name: 'meditation',
    path: '/app/meditation',
    segment: 'consumer',
    layout: 'simple',
    component: 'MeditationPage',
    guard: false,
    aliases: ['/meditation'],
  },
  {
    name: 'nyvee-test',
    path: '/test-nyvee',
    segment: 'public',
    layout: 'simple',
    component: 'NyveeTestPage',
    guard: false,
  },
  {
    name: 'test-accounts-dev',
    path: '/dev/test-accounts',
    segment: 'public',
    layout: 'minimal',
    component: 'TestAccountsPage',
    guard: false,
  },
  {
    name: 'nyvee-cocon',
    path: '/app/nyvee',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CNyveeCoconPage',
    guard: true,
  },
  {
    name: 'face-ar',
    path: '/app/face-ar',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CARFiltersPage',
    guard: true,
    aliases: ['/ar-filters'],
  },
  {
    name: 'bubble-beat',
    path: '/app/bubble-beat',
    segment: 'public',
    layout: 'simple',
    component: 'B2CBubbleBeatPage',
    guard: false,
    aliases: ['/bubble-beat'],
  },
  // Redirections obsolètes supprimées - utiliser /app/scan directement
  {
    name: 'voice-journal-redirect',
    path: '/app/voice-journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'RedirectToJournal',
    guard: true,
    aliases: ['/voice-journal'],
    deprecated: true,
  },
  // emotions route obsolète - alias vers scan
  {
    name: 'emotions-redirect',
    path: '/app/emotions',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'RedirectToScan',
    guard: true,
    aliases: ['/emotions'],
    deprecated: true,
  },
  {
    name: 'community',
    path: '/app/community',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CCommunautePage',
    guard: true,
    aliases: ['/community'],
  },
  {
    name: 'screen-silk',
    path: '/app/screen-silk',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CScreenSilkBreakPage',
    guard: true,
    aliases: ['/screen-silk-break'],
  },
  {
    name: 'vr-breath-guide',
    path: '/app/vr-breath-guide',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CVRBreathGuidePage',
    guard: true,
    aliases: ['/vr-breath-ariane'],
  },
  {
    name: 'vr-galaxy',
    path: '/app/vr-galaxy',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CVRGalaxyPage',
    guard: true,
    aliases: ['/vr-galactique'],
  },
  // Route fusionnée avec vr-breath-guide (ligne 505-513) - utiliser B2CVRBreathGuidePage
  {
    name: 'boss-grit',
    path: '/app/boss-grit',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CBossLevelGritPage',
    guard: true,
    aliases: ['/boss-level-grit'],
  },
  {
    name: 'mood-mixer',
    path: '/app/mood-mixer',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CMoodMixerPage',
    guard: true,
    aliases: ['/mood-mixer'],
  },
  {
    name: 'mood-presets-admin',
    path: '/app/mood-presets',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'MoodPresetsAdminPage',
    guard: true,
  },
  {
    name: 'ambition-arcade',
    path: '/app/ambition-arcade',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CAmbitionArcadePage',
    guard: true,
    aliases: ['/ambition-arcade'],
  },
  {
    name: 'bounce-back',
    path: '/app/bounce-back',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CBounceBackBattlePage',
    guard: true,
    aliases: ['/bounce-back-battle'],
  },
  {
    name: 'story-synth',
    path: '/app/story-synth',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CStorySynthLabPage',
    guard: true,
    aliases: ['/story-synth-lab'],
  },
  {
    name: 'social-cocon-b2c',
    path: '/app/social-cocon',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CSocialCoconPage',
    guard: true,
    aliases: ['/social-cocon'],
  },
  {
    name: 'communaute-b2c',
    path: '/app/communaute',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CCommunautePage',
    guard: true,
    aliases: ['/communaute'],
  },

  // ═══════════════════════════════════════════════════════════
  // PARC ÉMOTIONNEL (NAVIGATION & IMMERSION)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'emotional-park',
    path: '/app/emotional-park',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'EmotionalPark',
    guard: true,
    aliases: ['/parc', '/park'],
  },
  {
    name: 'park-journey',
    path: '/app/park-journey',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ParkJourney',
    guard: true,
    aliases: ['/voyage', '/journey'],
  },

  // ═══════════════════════════════════════════════════════════
  // ANALYTICS & DATA (CONSUMER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'analytics',
    path: '/app/analytics',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'AnalyticsPage',
    guard: true,
    aliases: ['/analytics'],
  },
  {
    name: 'leaderboard',
    path: '/app/leaderboard',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'LeaderboardPage',
    guard: true,
    aliases: ['/leaderboard'],
  },
  {
    name: 'gamification',
    path: '/gamification',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CGamificationPage',
    guard: true,
  },
  {
    name: 'activity',
    path: '/app/activity',
    segment: 'public',
    layout: 'simple',
    component: 'B2CActivitePage',
    guard: false,
    aliases: ['/activity-history'],
  },
  {
    name: 'heatmap',
    path: '/app/scores',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ScoresPage',
    guard: true,
    aliases: ['/app/heatmap', '/heatmap-vibes'],
  },
  
  // Routes supplémentaires
  // coach-chat supprimé - utiliser /app/coach
  // vr-sessions supprimé - fonctionnalité dans B2CVRBreathGuidePage
  {
    name: 'sessions',
    path: '/app/sessions',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'SessionsPage',
    guard: true,
  },
  {
    name: 'session-detail',
    path: '/app/sessions/:id',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'SessionDetailPage',
    guard: true,
  },
  {
    name: 'goals',
    path: '/app/goals',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GoalsPage',
    guard: true,
  },
  {
    name: 'goal-detail',
    path: '/app/goals/:id',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GoalDetailPage',
    guard: true,
  },
  {
    name: 'goal-new',
    path: '/app/goals/new',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'GoalNewPage',
    guard: true,
  },
  {
    name: 'park-achievements',
    path: '/app/park/achievements',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'AchievementsPage',
    guard: true,
  },
  {
    name: 'leaderboard',
    path: '/app/leaderboard',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'LeaderboardPage',
    guard: true,
  },
  {
    name: 'daily-challenges',
    path: '/app/daily-challenges',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'DailyChallengesPage',
    guard: true,
  },
  {
    name: 'badges',
    path: '/app/badges',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'BadgesPage',
    guard: true,
  },
  {
    name: 'rewards',
    path: '/app/rewards',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'RewardsPage',
    guard: true,
  },
  {
    name: 'challenges',
    path: '/app/challenges',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ChallengesPage',
    guard: true,
  },
  {
    name: 'challenge-detail',
    path: '/app/challenges/:id',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ChallengeDetailPage',
    guard: true,
  },
  {
    name: 'challenge-create',
    path: '/app/challenges/create',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ChallengeCreatePage',
    guard: true,
  },
  {
    name: 'notifications-center',
    path: '/app/notifications',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'NotificationsCenterPage',
    guard: true,
  },
  {
    name: 'premium',
    path: '/app/premium',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'PremiumPage',
    guard: false,
  },
  {
    name: 'billing',
    path: '/app/billing',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'BillingPage',
    guard: true,
  },
  {
    name: 'support',
    path: '/app/support',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'SupportPage',
    guard: false,
  },
  {
    name: 'faq',
    path: '/app/faq',
    segment: 'public',
    layout: 'simple',
    component: 'FAQPage',
    guard: false,
  },
  {
    name: 'tickets',
    path: '/app/tickets',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'TicketsPage',
    guard: true,
  },
  {
    name: 'insights',
    path: '/app/insights',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'InsightsPage',
    guard: true,
  },
  {
    name: 'trends',
    path: '/app/trends',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'TrendsPage',
    guard: true,
  },
  
  // ═══════════════════════════════════════════════════════════
  // PAGES EXISTANTES NON MAPPÉES (CONSOLIDATION)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'messages',
    path: '/messages',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'MessagesPage',
    guard: true,
    aliases: ['/chat', '/nyvee-chat'],
  },
  {
    name: 'calendar',
    path: '/calendar',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'CalendarPage',
    guard: true,
    aliases: ['/agenda'],
  },
  {
    name: 'point20',
    path: '/point20',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'Point20Page',
    guard: true,
    aliases: ['/recuperation-20'],
  },
  {
    name: 'test-page',
    path: '/test',
    segment: 'public',
    layout: 'simple',
    component: 'TestPage',
  },
  {
    name: 'journal-legacy',
    path: '/journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CJournalPage',
    guard: true,
    deprecated: true, // Redirection vers /app/journal
  },
  {
    name: 'music-legacy',
    path: '/music',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'B2CMusicEnhanced',
    guard: true,
    deprecated: true, // Redirection vers /app/music
  },
  // emotions-legacy supprimé - utiliser /app/scan directement
  {
    name: 'reporting',
    path: '/reporting',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ReportingPage',
    guard: true,
  },
  {
    name: 'export',
    path: '/export',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'ExportPage',
    guard: true,
  },
  // modules-journal supprimé - utiliser /app/journal

  // ═══════════════════════════════════════════════════════════
  // PARAMÈTRES & COMPTE
  // ═══════════════════════════════════════════════════════════
  {
    name: 'settings-general',
    path: '/settings/general',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CSettingsPage',
    guard: true,
    aliases: ['/settings', '/preferences'],
  },
  {
    name: 'settings-profile',
    path: '/settings/profile',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CProfileSettingsPage',
    guard: true,
    aliases: ['/profile-settings'],
  },
  {
    name: 'app-profile',
    path: '/app/profile',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CProfileSettingsPage',
    guard: true,
    aliases: ['/profile'],
  },
  {
    name: 'settings-privacy',
    path: '/settings/privacy',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CPrivacyTogglesPage',
    guard: true,
    aliases: ['/privacy-toggles', '/settings/data-privacy'],
  },
  {
    name: 'how-it-adapts',
    path: '/app/how-it-adapts',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'HowItAdaptsPage',
    guard: true,
  },
  {
    name: 'settings-notifications',
    path: '/settings/notifications',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CNotificationsPage',
    guard: true,
    aliases: ['/notifications'],
  },
  {
    name: 'settings-journal',
    path: '/settings/journal',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app-sidebar',
    component: 'JournalSettingsPage',
    guard: true,
  },

  // ═══════════════════════════════════════════════════════════
  // B2B FEATURES (EMPLOYEE)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'teams',
    path: '/app/teams',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BTeamsPage',
    guard: true,
    aliases: ['/teams'],
  },
  {
    name: 'social-cocon-b2b',
    path: '/app/social',
    segment: 'employee',
    role: 'employee',
    layout: 'app',
    component: 'B2BSocialCoconPage',
    guard: true,
  },

  // ═══════════════════════════════════════════════════════════
  // B2B ADMIN (MANAGER)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'admin-reports',
    path: '/app/reports',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BReportsPage',
    guard: true,
    aliases: ['/reports'],
  },
  {
    name: 'admin-reports-period',
    path: '/app/reports/:period',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BReportDetailPage',
    guard: true,
  },
  {
    name: 'admin-events',
    path: '/app/events',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BEventsPage',
    guard: true,
    aliases: ['/events'],
  },
  {
    name: 'admin-optimization',
    path: '/app/optimization',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BOptimisationPage',
    guard: true,
    aliases: ['/optimisation'],
  },
  {
    name: 'admin-security',
    path: '/app/security',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BSecurityPage',
    guard: true,
    aliases: ['/security'],
  },
  {
    name: 'admin-audit',
    path: '/app/audit',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BAuditPage',
    guard: true,
    aliases: ['/audit'],
  },
  {
    name: 'admin-music-analytics',
    path: '/app/admin/music-analytics',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'MusicAnalyticsDashboard',
    guard: true,
  },
  {
    name: 'admin-accessibility',
    path: '/app/accessibility',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'B2BAccessibilityPage',
    guard: true,
    aliases: ['/accessibility'],
  },
  {
    name: 'admin-gdpr-unified',
    path: '/admin/gdpr',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'UnifiedGDPRDashboard',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-api-monitoring',
    path: '/admin/api-monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'APIMonitoringDashboard',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-cron-monitoring',
    path: '/admin/cron-monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'GamificationCronMonitoring',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-music-queue',
    path: '/admin/music-queue',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'MusicQueueAdminPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-music-metrics',
    path: '/admin/music-metrics',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'MusicQueueMetricsPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-user-roles',
    path: '/admin/user-roles',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'UserRolesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'challenges-history',
    path: '/app/challenges/history',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'ChallengesHistory',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'create-custom-challenge',
    path: '/admin/challenges/create',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'CreateCustomChallenge',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'edit-custom-challenge',
    path: '/admin/challenges/edit/:id',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'EditCustomChallenge',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'challenges-dashboard',
    path: '/admin/challenges',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'ChallengesDashboard',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'achievements',
    path: '/app/achievements',
    segment: 'consumer',
    role: 'consumer',
    layout: 'app',
    component: 'Achievements',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-system-health',
    path: '/admin/system-health',
    segment: 'admin',
    role: 'admin',
    layout: 'app',
    component: 'AdminSystemHealthPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-monitoring-dashboard',
    path: '/admin/monitoring',
    segment: 'admin',
    role: 'admin',
    layout: 'app',
    component: 'MonitoringDashboard',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-ai-monitoring',
    path: '/admin/ai-monitoring',
    segment: 'admin',
    role: 'admin',
    layout: 'app',
    component: 'AIMonitoringDashboard',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-config',
    path: '/admin/alert-config',
    segment: 'admin',
    role: 'admin',
    layout: 'app',
    component: 'AlertConfigurationPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-analytics',
    path: '/admin/alert-analytics',
    segment: 'admin',
    role: 'admin',
    layout: 'app',
    component: 'AlertAnalyticsDashboard',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'admin-alert-templates',
    path: '/admin/alert-templates',
    segment: 'admin',
    role: 'admin',
    layout: 'app',
    component: 'AlertTemplatesPage',
    guard: true,
    requireAuth: true,
  },
  {
    name: 'gdpr-cron-monitoring',
    path: '/gdpr/cron-monitoring',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'CronMonitoring',
    guard: true,
  },
  {
    name: 'gdpr-blockchain-backups',
    path: '/gdpr/blockchain-backups',
    segment: 'manager',
    role: 'manager',
    layout: 'app',
    component: 'BlockchainBackups',
    guard: true,
  },

  
  // ═══════════════════════════════════════════════════════════
  // TOOLS & NAVIGATION PAGES
  // ═══════════════════════════════════════════════════════════
  // Routes supprimées (pages orphelines nettoyées)
  // - NavigationPage (supprimée)
  // - CompleteFeatureMatrix (supprimée) 
  // - MissingPagesManifest (supprimée)

  // ═══════════════════════════════════════════════════════════
  // DÉVELOPPEMENT (UNIQUEMENT SI DEBUG)
  // ═══════════════════════════════════════════════════════════
  ...(process.env.NODE_ENV === 'development' ? [
    {
      name: 'validation',
      path: '/validation',
      segment: 'public',
      layout: 'simple',
      component: 'ValidationPage',
    }
  ] : []),

  // ═══════════════════════════════════════════════════════════
  // DEV-ONLY ROUTES (Masquées en production)
  // ═══════════════════════════════════════════════════════════
  // Routes de développement masquées en production
  ...(import.meta.env.DEV ? [
    {
      name: 'comprehensive-system-audit',
      path: '/dev/system-audit',
      segment: 'public',
      layout: 'app',
      component: 'ComprehensiveSystemAuditPage',
      guard: false,
    },
    {
      name: 'dev-error-boundary',
      path: '/dev/error-boundary',
      segment: 'public',
      layout: 'marketing',
      component: 'ErrorBoundaryTestPage',
      guard: false,
    },
  // Routes de debug supprimées (pages orphelines nettoyées)
  // - DiagnosticPage (supprimée)
  // - SystemValidationPage (supprimée) 
  // - SystemRepairPage (supprimée)
  ] : []),

  // ═══════════════════════════════════════════════════════════
  // PAGES SYSTÈME
  // ═══════════════════════════════════════════════════════════
  {
    name: 'unauthorized',
    path: '/401',
    segment: 'public',
    layout: 'marketing',
    component: 'UnauthorizedPage',
  },
  {
    name: 'forbidden',
    path: '/403',
    segment: 'public',
    layout: 'marketing',
    component: 'ForbiddenPage',
  },
  {
    name: 'not-found',
    path: '/404',
    segment: 'public',
    layout: 'marketing',
    component: 'UnifiedErrorPage',
  },
  {
    name: 'server-error',
    path: '/500',
    segment: 'public',
    layout: 'marketing',
    component: 'ServerErrorPage',
  },
  
  // ═══════════════════════════════════════════════════════════
  // LEGAL & COMPLIANCE PAGES - Déjà défini aux lignes 91-136
  // ═══════════════════════════════════════════════════════════
  
  // ═══════════════════════════════════════════════════════════
  // BILLING & SUBSCRIPTION
  // ═══════════════════════════════════════════════════════════
  {
    name: 'subscribe',
    path: '/subscribe',
    segment: 'consumer',
    layout: 'app',
    component: 'SubscribePage',
    guard: true,
    aliases: ['/billing', '/plans'],
  },

  // ═══════════════════════════════════════════════════════════
  // NOUVELLES ROUTES - COMPLEMENTAIRES
  // ═══════════════════════════════════════════════════════════
  
  // Audio & Voice
  // journal-audio supprimé - fonctionnalité dans B2CJournalPage
  {
    name: 'voice-analysis',
    path: '/app/voice-analysis',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'VoiceAnalysisPage',
    guard: true,
  },
  
  // Social
  {
    name: 'friends',
    path: '/app/friends',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'FriendsPage',
    guard: true,
  },
  {
    name: 'groups',
    path: '/app/groups',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'GroupsPage',
    guard: true,
  },
  {
    name: 'feed',
    path: '/app/feed',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'B2CCommunautePage',
    guard: true,
  },
  
  // Personnalisation
  {
    name: 'themes',
    path: '/app/themes',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'ThemesPage',
    guard: true,
  },
  {
    name: 'customization',
    path: '/app/customization',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'CustomizationPage',
    guard: true,
  },
  {
    name: 'widgets',
    path: '/app/widgets',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'WidgetsPage',
    guard: true,
  },
  
  // Événements & Ateliers
  {
    name: 'events-calendar',
    path: '/app/events/calendar',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'EventsCalendarPage',
    guard: true,
  },
  {
    name: 'workshops',
    path: '/app/workshops',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'WorkshopsPage',
    guard: true,
  },
  {
    name: 'webinars',
    path: '/app/webinars',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'WebinarsPage',
    guard: true,
  },
  
  // Export & Partage
  {
    name: 'export-pdf',
    path: '/app/export/pdf',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'ExportPDFPage',
    guard: true,
  },
  {
    name: 'export-csv',
    path: '/app/export/csv',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'ExportCSVPage',
    guard: true,
  },
  {
    name: 'share-data',
    path: '/app/share',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'ShareDataPage',
    guard: true,
  },
  
  // Intégrations
  {
    name: 'integrations',
    path: '/app/integrations',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'IntegrationsPage',
    guard: true,
  },
  {
    name: 'api-keys',
    path: '/app/api-keys',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'APIKeysPage',
    guard: true,
  },
  {
    name: 'webhooks',
    path: '/app/webhooks',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'WebhooksPage',
    guard: true,
  },
  
  // Accessibilité
  {
    name: 'accessibility-settings',
    path: '/app/accessibility-settings',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'AccessibilitySettingsPage',
    guard: true,
  },
  {
    name: 'shortcuts',
    path: '/app/shortcuts',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'ShortcutsPage',
    guard: true,
  },
  
  // Rapports
  {
    name: 'weekly-report',
    path: '/app/reports/weekly',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'WeeklyReportPage',
    guard: true,
  },
  {
    name: 'monthly-report',
    path: '/app/reports/monthly',
    segment: 'consumer',
    layout: 'app-sidebar',
    component: 'MonthlyReportPage',
    guard: true,
  },
  
  // Navigation Hub
  {
    name: 'navigation-hub',
    path: '/navigation',
    segment: 'consumer',
    layout: 'simple',
    component: 'NavigationPage',
    guard: false,
    meta: {
      title: 'Navigation - EmotionsCare',
      description: 'Explorez toutes les fonctionnalités EmotionsCare',
    },
  },

  // ═══════════════════════════════════════════════════════════
  // SYSTEM & MONITORING
  // ═══════════════════════════════════════════════════════════
  {
    name: 'system-health',
    path: '/system-health',
    segment: 'public',
    layout: 'app',
    component: 'SystemHealthPage',
    guard: false,
    meta: {
      title: 'Santé Système - EmotionsCare',
      description: 'Monitoring et santé du système',
    },
  },
  {
    name: 'k6-analytics',
    path: '/k6-analytics',
    segment: 'public',
    layout: 'app',
    component: 'K6AnalyticsDashboard',
    guard: false,
    meta: {
      title: 'K6 Analytics - EmotionsCare',
      description: 'Dashboard analytics des tests de charge K6',
    },
  },

  // ═══════════════════════════════════════════════════════════
  // 404 FALLBACK ROUTE (must be last)
  // ═══════════════════════════════════════════════════════════
  {
    name: 'catch-all',
    path: '*',
    segment: 'public',
    layout: 'simple',
    component: 'UnifiedErrorPage',
    meta: {
      title: 'Page introuvable - EmotionsCare',
      description: 'Cette page n\'existe pas',
    },
  },
];