import type {
  InstrumentCatalog,
  InstrumentCode,
  LocaleCode,
} from '../../clinicalScoringService';

type CatalogByLocale = Partial<Record<LocaleCode, InstrumentCatalog>>;

type CatalogDictionary = Partial<Record<InstrumentCode, CatalogByLocale>>;

export const ADDITIONAL_CATALOGS: CatalogDictionary = {
  AAQ2: {
    fr: {
      code: 'AAQ2',
      locale: 'fr',
      name: 'Souplesse face aux pensées',
      version: '1.0',
      expiryMinutes: 45,
      items: [
        { id: '1', prompt: 'Je sens que des souvenirs douloureux freinent ma vie', type: 'scale', min: 1, max: 7 },
        { id: '2', prompt: 'J’appréhende l’intensité de mes émotions', type: 'scale', min: 1, max: 7 },
        { id: '3', prompt: 'Je redoute de perdre la maîtrise de mes pensées', type: 'scale', min: 1, max: 7 },
        { id: '4', prompt: 'Mes ressentis difficiles me coupent de ce qui compte', type: 'scale', min: 1, max: 7 },
        { id: '5', prompt: 'Mes émotions créent des nœuds dans mon quotidien', type: 'scale', min: 1, max: 7 },
        { id: '6', prompt: 'J’ai l’impression que les autres gèrent mieux que moi', type: 'scale', min: 1, max: 7 },
        { id: '7', prompt: 'Mes inquiétudes barrent mes projets', type: 'scale', min: 1, max: 7 },
      ],
    },
    en: {
      code: 'AAQ2',
      locale: 'en',
      name: 'Flexibility with inner events',
      version: '1.0',
      expiryMinutes: 45,
      items: [
        { id: '1', prompt: 'Painful memories seem to slow my life', type: 'scale', min: 1, max: 7 },
        { id: '2', prompt: 'I feel wary of intense emotions', type: 'scale', min: 1, max: 7 },
        { id: '3', prompt: 'I fear losing grip on my thoughts', type: 'scale', min: 1, max: 7 },
        { id: '4', prompt: 'Hard feelings pull me away from what matters', type: 'scale', min: 1, max: 7 },
        { id: '5', prompt: 'Emotions create knots in my day', type: 'scale', min: 1, max: 7 },
        { id: '6', prompt: 'It seems others handle life better than I do', type: 'scale', min: 1, max: 7 },
        { id: '7', prompt: 'Worries block my projects', type: 'scale', min: 1, max: 7 },
      ],
    },
  },
  POMS: {
    fr: {
      code: 'POMS',
      locale: 'fr',
      name: 'Profil d’humeur condensé',
      version: '1.0',
      expiryMinutes: 50,
      items: [
        { id: '1', prompt: 'Je me sens tendu·e intérieurement', type: 'scale', min: 0, max: 4, subscale: 'tension' },
        { id: '2', prompt: 'Mon corps reste en alerte', type: 'scale', min: 0, max: 4, subscale: 'tension' },
        { id: '3', prompt: 'Je ressens une nervosité diffuse', type: 'scale', min: 0, max: 4, subscale: 'tension' },
        { id: '4', prompt: 'J’ai du mal à relâcher la pression', type: 'scale', min: 0, max: 4, subscale: 'tension' },
        { id: '5', prompt: 'Je me sens abattu·e', type: 'scale', min: 0, max: 4, subscale: 'depression' },
        { id: '6', prompt: 'J’ai du mal à trouver de l’intérêt', type: 'scale', min: 0, max: 4, subscale: 'depression' },
        { id: '7', prompt: 'Je me sens découragé·e', type: 'scale', min: 0, max: 4, subscale: 'depression' },
        { id: '8', prompt: 'Je vois peu d’élan autour de moi', type: 'scale', min: 0, max: 4, subscale: 'depression' },
        { id: '9', prompt: 'Je me sens irrité·e', type: 'scale', min: 0, max: 4, subscale: 'anger' },
        { id: '10', prompt: 'Je suis contrarié·e par peu de choses', type: 'scale', min: 0, max: 4, subscale: 'anger' },
        { id: '11', prompt: 'Je sens monter de la colère', type: 'scale', min: 0, max: 4, subscale: 'anger' },
        { id: '12', prompt: 'Je garde de la rancœur', type: 'scale', min: 0, max: 4, subscale: 'anger' },
        { id: '13', prompt: 'Je me sens vidé·e d’énergie', type: 'scale', min: 0, max: 4, subscale: 'fatigue' },
        { id: '14', prompt: 'Mon corps paraît lourd', type: 'scale', min: 0, max: 4, subscale: 'fatigue' },
        { id: '15', prompt: 'Je lutte pour rester éveillé·e', type: 'scale', min: 0, max: 4, subscale: 'fatigue' },
        { id: '16', prompt: 'Je manque d’élan physique', type: 'scale', min: 0, max: 4, subscale: 'fatigue' },
        { id: '17', prompt: 'Je me sens dans le brouillard', type: 'scale', min: 0, max: 4, subscale: 'confusion' },
        { id: '18', prompt: 'Je peine à me concentrer', type: 'scale', min: 0, max: 4, subscale: 'confusion' },
        { id: '19', prompt: 'Mes pensées se dispersent', type: 'scale', min: 0, max: 4, subscale: 'confusion' },
        { id: '20', prompt: 'Je dois faire des efforts pour rester clair·e', type: 'scale', min: 0, max: 4, subscale: 'confusion' },
        { id: '21', prompt: 'Je me sens rempli·e d’entrain', type: 'scale', min: 0, max: 4, subscale: 'vigor' },
        { id: '22', prompt: 'Je me sens plein·e d’énergie créative', type: 'scale', min: 0, max: 4, subscale: 'vigor' },
        { id: '23', prompt: 'Je me sens positif·ve et vif·ve', type: 'scale', min: 0, max: 4, subscale: 'vigor' },
        { id: '24', prompt: 'Je me sens prêt·e à relever des défis', type: 'scale', min: 0, max: 4, subscale: 'vigor' },
      ],
    },
    en: {
      code: 'POMS',
      locale: 'en',
      name: 'Mood profile short form',
      version: '1.0',
      expiryMinutes: 50,
      items: [
        { id: '1', prompt: 'I feel inner tension', type: 'scale', min: 0, max: 4, subscale: 'tension' },
        { id: '2', prompt: 'My body stays on alert', type: 'scale', min: 0, max: 4, subscale: 'tension' },
        { id: '3', prompt: 'A diffuse nervousness is present', type: 'scale', min: 0, max: 4, subscale: 'tension' },
        { id: '4', prompt: 'Letting go feels difficult', type: 'scale', min: 0, max: 4, subscale: 'tension' },
        { id: '5', prompt: 'I feel low in spirit', type: 'scale', min: 0, max: 4, subscale: 'depression' },
        { id: '6', prompt: 'It is hard to find interest', type: 'scale', min: 0, max: 4, subscale: 'depression' },
        { id: '7', prompt: 'I feel discouraged', type: 'scale', min: 0, max: 4, subscale: 'depression' },
        { id: '8', prompt: 'I sense little drive around me', type: 'scale', min: 0, max: 4, subscale: 'depression' },
        { id: '9', prompt: 'I feel irritated', type: 'scale', min: 0, max: 4, subscale: 'anger' },
        { id: '10', prompt: 'Small things upset me', type: 'scale', min: 0, max: 4, subscale: 'anger' },
        { id: '11', prompt: 'I sense anger rising', type: 'scale', min: 0, max: 4, subscale: 'anger' },
        { id: '12', prompt: 'I hold on to resentment', type: 'scale', min: 0, max: 4, subscale: 'anger' },
        { id: '13', prompt: 'I feel drained of energy', type: 'scale', min: 0, max: 4, subscale: 'fatigue' },
        { id: '14', prompt: 'My body feels heavy', type: 'scale', min: 0, max: 4, subscale: 'fatigue' },
        { id: '15', prompt: 'Staying awake is a struggle', type: 'scale', min: 0, max: 4, subscale: 'fatigue' },
        { id: '16', prompt: 'I miss physical drive', type: 'scale', min: 0, max: 4, subscale: 'fatigue' },
        { id: '17', prompt: 'I feel in a mental fog', type: 'scale', min: 0, max: 4, subscale: 'confusion' },
        { id: '18', prompt: 'I struggle to focus', type: 'scale', min: 0, max: 4, subscale: 'confusion' },
        { id: '19', prompt: 'My thoughts scatter easily', type: 'scale', min: 0, max: 4, subscale: 'confusion' },
        { id: '20', prompt: 'I must work to stay clear', type: 'scale', min: 0, max: 4, subscale: 'confusion' },
        { id: '21', prompt: 'I feel full of drive', type: 'scale', min: 0, max: 4, subscale: 'vigor' },
        { id: '22', prompt: 'Creative energy fills me', type: 'scale', min: 0, max: 4, subscale: 'vigor' },
        { id: '23', prompt: 'I feel positive and lively', type: 'scale', min: 0, max: 4, subscale: 'vigor' },
        { id: '24', prompt: 'I feel ready to take on challenges', type: 'scale', min: 0, max: 4, subscale: 'vigor' },
      ],
    },
  },
  ISI: {
    fr: {
      code: 'ISI',
      locale: 'fr',
      name: 'Vigilance sommeil',
      version: '1.0',
      expiryMinutes: 40,
      items: [
        { id: '1', prompt: 'Difficulté à m’endormir', type: 'scale', min: 0, max: 4 },
        { id: '2', prompt: 'Réveils pendant la nuit', type: 'scale', min: 0, max: 4 },
        { id: '3', prompt: 'Réveil trop tôt le matin', type: 'scale', min: 0, max: 4 },
        { id: '4', prompt: 'Satisfaction par rapport à mon sommeil', type: 'scale', min: 0, max: 4, reversed: true },
        { id: '5', prompt: 'Impact du sommeil sur mes activités', type: 'scale', min: 0, max: 4 },
        { id: '6', prompt: 'Préoccupation de mon entourage pour mon sommeil', type: 'scale', min: 0, max: 4 },
        { id: '7', prompt: 'Niveau d’inquiétude face à mon sommeil', type: 'scale', min: 0, max: 4 },
      ],
    },
    en: {
      code: 'ISI',
      locale: 'en',
      name: 'Sleep vigilance check',
      version: '1.0',
      expiryMinutes: 40,
      items: [
        { id: '1', prompt: 'Difficulty falling asleep', type: 'scale', min: 0, max: 4 },
        { id: '2', prompt: 'Waking up during the night', type: 'scale', min: 0, max: 4 },
        { id: '3', prompt: 'Waking earlier than desired', type: 'scale', min: 0, max: 4 },
        { id: '4', prompt: 'Satisfaction with my sleep', type: 'scale', min: 0, max: 4, reversed: true },
        { id: '5', prompt: 'Impact of sleep on daily activities', type: 'scale', min: 0, max: 4 },
        { id: '6', prompt: 'People around me notice my sleep issues', type: 'scale', min: 0, max: 4 },
        { id: '7', prompt: 'Level of worry about my sleep', type: 'scale', min: 0, max: 4 },
      ],
    },
  },
  GAS: {
    fr: {
      code: 'GAS',
      locale: 'fr',
      name: 'Cap vers l’objectif',
      version: '1.0',
      expiryMinutes: 35,
      items: [
        { id: '1', prompt: 'Je clarifie l’objectif que je poursuis', type: 'scale', min: 0, max: 4 },
        { id: '2', prompt: 'Je visualise les étapes importantes', type: 'scale', min: 0, max: 4 },
        { id: '3', prompt: 'Je sens du soutien autour de cet objectif', type: 'scale', min: 0, max: 4 },
        { id: '4', prompt: 'Je progresse au rythme espéré', type: 'scale', min: 0, max: 4 },
        { id: '5', prompt: 'Je célèbre les jalons atteints', type: 'scale', min: 0, max: 4 },
      ],
    },
    en: {
      code: 'GAS',
      locale: 'en',
      name: 'Goal alignment snapshot',
      version: '1.0',
      expiryMinutes: 35,
      items: [
        { id: '1', prompt: 'I clarify the goal I am pursuing', type: 'scale', min: 0, max: 4 },
        { id: '2', prompt: 'I can picture the key steps', type: 'scale', min: 0, max: 4 },
        { id: '3', prompt: 'I feel supported around this goal', type: 'scale', min: 0, max: 4 },
        { id: '4', prompt: 'I move forward at the pace I hoped for', type: 'scale', min: 0, max: 4 },
        { id: '5', prompt: 'I celebrate the milestones reached', type: 'scale', min: 0, max: 4 },
      ],
    },
  },
  GRITS: {
    fr: {
      code: 'GRITS',
      locale: 'fr',
      name: 'Persévérance en action',
      version: '1.0',
      expiryMinutes: 40,
      items: [
        { id: '1', prompt: 'Les nouvelles idées me détournent vite de mes projets', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '2', prompt: 'Les contretemps ne me découragent pas', type: 'scale', min: 1, max: 5 },
        { id: '3', prompt: 'Je me lasse rapidement d’un centre d’intérêt', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '4', prompt: 'Je travaille avec constance', type: 'scale', min: 1, max: 5 },
        { id: '5', prompt: 'Je change souvent de but en cours de route', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '6', prompt: 'Je peine à rester concentré·e sur les projets longs', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '7', prompt: 'Je termine ce que je commence', type: 'scale', min: 1, max: 5 },
        { id: '8', prompt: 'Je suis persévérant·e', type: 'scale', min: 1, max: 5 },
      ],
    },
    en: {
      code: 'GRITS',
      locale: 'en',
      name: 'Grit short pulse',
      version: '1.0',
      expiryMinutes: 40,
      items: [
        { id: '1', prompt: 'New ideas quickly pull me from projects', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '2', prompt: 'Setbacks do not discourage me', type: 'scale', min: 1, max: 5 },
        { id: '3', prompt: 'I lose interest in a topic quickly', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '4', prompt: 'I work with steady effort', type: 'scale', min: 1, max: 5 },
        { id: '5', prompt: 'I often switch goals mid-course', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '6', prompt: 'Long projects are hard to stay with', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '7', prompt: 'I finish whatever I begin', type: 'scale', min: 1, max: 5 },
        { id: '8', prompt: 'I am diligent', type: 'scale', min: 1, max: 5 },
      ],
    },
  },
  BRS: {
    fr: {
      code: 'BRS',
      locale: 'fr',
      name: 'Rebond résilient',
      version: '1.0',
      expiryMinutes: 30,
      items: [
        { id: '1', prompt: 'Je rebondis vite après une difficulté', type: 'scale', min: 1, max: 5 },
        { id: '2', prompt: 'Il m’est difficile de traverser des situations stressantes', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '3', prompt: 'Je reprends vite le dessus après un revers', type: 'scale', min: 1, max: 5 },
        { id: '4', prompt: 'J’ai du mal à me remettre d’événements désagréables', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '5', prompt: 'Je trouve du positif après un obstacle', type: 'scale', min: 1, max: 5 },
        { id: '6', prompt: 'Je me sens vite submergé·e lors d’un contretemps', type: 'scale', min: 1, max: 5, reversed: true },
      ],
    },
    en: {
      code: 'BRS',
      locale: 'en',
      name: 'Brief resilience check',
      version: '1.0',
      expiryMinutes: 30,
      items: [
        { id: '1', prompt: 'I bounce back quickly after difficulty', type: 'scale', min: 1, max: 5 },
        { id: '2', prompt: 'It is hard for me to get through stress', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '3', prompt: 'I quickly regain control after a setback', type: 'scale', min: 1, max: 5 },
        { id: '4', prompt: 'Recovering from unpleasant events is hard', type: 'scale', min: 1, max: 5, reversed: true },
        { id: '5', prompt: 'I find positives after obstacles', type: 'scale', min: 1, max: 5 },
        { id: '6', prompt: 'I feel overwhelmed when setbacks appear', type: 'scale', min: 1, max: 5, reversed: true },
      ],
    },
  },
  CVSQ: {
    fr: {
      code: 'CVSQ',
      locale: 'fr',
      name: 'Confort visuel numérique',
      version: '1.0',
      expiryMinutes: 25,
      items: [
        { id: '1', prompt: 'Mes yeux picotent après le temps d’écran', type: 'scale', min: 0, max: 3 },
        { id: '2', prompt: 'Je ressens une sécheresse oculaire', type: 'scale', min: 0, max: 3 },
        { id: '3', prompt: 'Ma vision devient floue temporairement', type: 'scale', min: 0, max: 3 },
        { id: '4', prompt: 'Je ressens des maux de tête liés à l’écran', type: 'scale', min: 0, max: 3 },
        { id: '5', prompt: 'Je dois frotter mes yeux pour soulager', type: 'scale', min: 0, max: 3 },
        { id: '6', prompt: 'La lumière de l’écran m’éblouit', type: 'scale', min: 0, max: 3 },
        { id: '7', prompt: 'Je cligne souvent pour retrouver la netteté', type: 'scale', min: 0, max: 3 },
        { id: '8', prompt: 'Je ressens des tensions dans la nuque ou les épaules', type: 'scale', min: 0, max: 3 },
      ],
    },
    en: {
      code: 'CVSQ',
      locale: 'en',
      name: 'Digital visual comfort',
      version: '1.0',
      expiryMinutes: 25,
      items: [
        { id: '1', prompt: 'My eyes tingle after screen time', type: 'scale', min: 0, max: 3 },
        { id: '2', prompt: 'I notice eye dryness', type: 'scale', min: 0, max: 3 },
        { id: '3', prompt: 'My vision turns blurry for a moment', type: 'scale', min: 0, max: 3 },
        { id: '4', prompt: 'I experience screen related headaches', type: 'scale', min: 0, max: 3 },
        { id: '5', prompt: 'I need to rub my eyes for relief', type: 'scale', min: 0, max: 3 },
        { id: '6', prompt: 'Screen light feels dazzling', type: 'scale', min: 0, max: 3 },
        { id: '7', prompt: 'I blink often to regain clarity', type: 'scale', min: 0, max: 3 },
        { id: '8', prompt: 'I feel neck or shoulder tension while using screens', type: 'scale', min: 0, max: 3 },
      ],
    },
  },
  SWEMWBS: {
    fr: {
      code: 'SWEMWBS',
      locale: 'fr',
      name: 'Bien-être essentiel',
      version: '1.0',
      expiryMinutes: 35,
      items: [
        { id: '1', prompt: 'Je me sens optimiste pour l’avenir', type: 'scale', min: 1, max: 5 },
        { id: '2', prompt: 'Je me sens utile', type: 'scale', min: 1, max: 5 },
        { id: '3', prompt: 'Je me sens détendu·e', type: 'scale', min: 1, max: 5 },
        { id: '4', prompt: 'Je gère bien les difficultés', type: 'scale', min: 1, max: 5 },
        { id: '5', prompt: 'Je pense avec clarté', type: 'scale', min: 1, max: 5 },
        { id: '6', prompt: 'Je me sens proche des autres', type: 'scale', min: 1, max: 5 },
        { id: '7', prompt: 'Je prends des décisions avec assurance', type: 'scale', min: 1, max: 5 },
      ],
    },
    en: {
      code: 'SWEMWBS',
      locale: 'en',
      name: 'Core wellbeing pulse',
      version: '1.0',
      expiryMinutes: 35,
      items: [
        { id: '1', prompt: 'I feel optimistic about the future', type: 'scale', min: 1, max: 5 },
        { id: '2', prompt: 'I feel useful', type: 'scale', min: 1, max: 5 },
        { id: '3', prompt: 'I feel relaxed', type: 'scale', min: 1, max: 5 },
        { id: '4', prompt: 'I handle problems well', type: 'scale', min: 1, max: 5 },
        { id: '5', prompt: 'I think clearly', type: 'scale', min: 1, max: 5 },
        { id: '6', prompt: 'I feel close to other people', type: 'scale', min: 1, max: 5 },
        { id: '7', prompt: 'I make decisions with confidence', type: 'scale', min: 1, max: 5 },
      ],
    },
  },
};
