name: E2E

on:
  pull_request:

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  PREVIEW_URL: ${{ secrets.PREVIEW_URL }}
  NODE_ENV: test

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - name: Seed DB (idempotent)
        run: pnpm seed:ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run E2E
        run: pnpm e2e
        env:
          PREVIEW_URL: ${{ env.PREVIEW_URL }}

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report
            test-results
