name: Lighthouse

on:
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run lhci
        env:
          PREVIEW_URL: ${{ secrets.PREVIEW_URL }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lhci-report
          path: .lighthouseci
