name: Lighthouse

on:
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Install Chrome for Lighthouse
        run: npx @puppeteer/browsers install chrome@stable
      - name: Run Lighthouse CI
        run: npm run lhci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          CHROME_PATH: ${{ github.workspace }}/chrome/*/chrome-linux64/chrome
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lhci-report
          path: .lighthouseci
