name: Validate Data (D.1)

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - "sql/**"
      - ".github/workflows/validate-data.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL_STAGING }}  # ex: postgres://user:pass@host:5432/dbname
    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run validation SQL
        id: runsql
        run: |
          set -e
          # Exécute et capture la sortie en TSV (facile à parser)
          psql "$DB_URL" -f sql/007_validation_data.sql -v ON_ERROR_STOP=1 -P pager=off -A -F $'\t' > validation.tsv || true
          echo "---- Result lines ----"
          cat validation.tsv || true
          lines=$(wc -l < validation.tsv | tr -d ' ')
          echo "lines=$lines" >> $GITHUB_OUTPUT

      - name: Fail if anomalies
        if: steps.runsql.outputs.lines != '0'
        run: |
          echo "::error::Data validation found anomalies:"
          cat validation.tsv
          exit 1

      - name: Success note
        if: steps.runsql.outputs.lines == '0'
        run: echo "Data validation passed (no anomalies)."
